// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AccountUpdateMulti.proto
// Protobuf C++ Version: 5.29.3

#include "AccountUpdateMulti.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {

inline constexpr AccountUpdateMulti::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        account_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        modelcode_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        currency_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        reqid_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AccountUpdateMulti::AccountUpdateMulti(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AccountUpdateMultiDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AccountUpdateMultiDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AccountUpdateMultiDefaultTypeInternal() {}
  union {
    AccountUpdateMulti _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AccountUpdateMultiDefaultTypeInternal _AccountUpdateMulti_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_AccountUpdateMulti_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_AccountUpdateMulti_2eproto = nullptr;
const ::uint32_t
    TableStruct_AccountUpdateMulti_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protobuf::AccountUpdateMulti, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::AccountUpdateMulti, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::AccountUpdateMulti, _impl_.reqid_),
        PROTOBUF_FIELD_OFFSET(::protobuf::AccountUpdateMulti, _impl_.account_),
        PROTOBUF_FIELD_OFFSET(::protobuf::AccountUpdateMulti, _impl_.modelcode_),
        PROTOBUF_FIELD_OFFSET(::protobuf::AccountUpdateMulti, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::protobuf::AccountUpdateMulti, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::protobuf::AccountUpdateMulti, _impl_.currency_),
        5,
        0,
        1,
        2,
        3,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 14, -1, sizeof(::protobuf::AccountUpdateMulti)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_AccountUpdateMulti_default_instance_._instance,
};
const char descriptor_table_protodef_AccountUpdateMulti_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030AccountUpdateMulti.proto\022\010protobuf\"\326\001\n"
    "\022AccountUpdateMulti\022\022\n\005reqId\030\001 \001(\005H\000\210\001\001\022"
    "\024\n\007account\030\002 \001(\tH\001\210\001\001\022\026\n\tmodelCode\030\003 \001(\t"
    "H\002\210\001\001\022\020\n\003key\030\004 \001(\tH\003\210\001\001\022\022\n\005value\030\005 \001(\tH\004"
    "\210\001\001\022\025\n\010currency\030\006 \001(\tH\005\210\001\001B\010\n\006_reqIdB\n\n\010"
    "_accountB\014\n\n_modelCodeB\006\n\004_keyB\010\n\006_value"
    "B\013\n\t_currencyBB\n\026com.ib.client.protobufB"
    "\027AccountUpdateMultiProto\252\002\016IBApi.protobu"
    "fb\006proto3"
};
static ::absl::once_flag descriptor_table_AccountUpdateMulti_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_AccountUpdateMulti_2eproto = {
    false,
    false,
    329,
    descriptor_table_protodef_AccountUpdateMulti_2eproto,
    "AccountUpdateMulti.proto",
    &descriptor_table_AccountUpdateMulti_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_AccountUpdateMulti_2eproto::offsets,
    file_level_enum_descriptors_AccountUpdateMulti_2eproto,
    file_level_service_descriptors_AccountUpdateMulti_2eproto,
};
namespace protobuf {
// ===================================================================

class AccountUpdateMulti::_Internal {
 public:
  using HasBits =
      decltype(std::declval<AccountUpdateMulti>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_._has_bits_);
};

AccountUpdateMulti::AccountUpdateMulti(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.AccountUpdateMulti)
}
inline PROTOBUF_NDEBUG_INLINE AccountUpdateMulti::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protobuf::AccountUpdateMulti& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        account_(arena, from.account_),
        modelcode_(arena, from.modelcode_),
        key_(arena, from.key_),
        value_(arena, from.value_),
        currency_(arena, from.currency_) {}

AccountUpdateMulti::AccountUpdateMulti(
    ::google::protobuf::Arena* arena,
    const AccountUpdateMulti& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AccountUpdateMulti* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.reqid_ = from._impl_.reqid_;

  // @@protoc_insertion_point(copy_constructor:protobuf.AccountUpdateMulti)
}
inline PROTOBUF_NDEBUG_INLINE AccountUpdateMulti::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        account_(arena),
        modelcode_(arena),
        key_(arena),
        value_(arena),
        currency_(arena) {}

inline void AccountUpdateMulti::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.reqid_ = {};
}
AccountUpdateMulti::~AccountUpdateMulti() {
  // @@protoc_insertion_point(destructor:protobuf.AccountUpdateMulti)
  SharedDtor(*this);
}
inline void AccountUpdateMulti::SharedDtor(MessageLite& self) {
  AccountUpdateMulti& this_ = static_cast<AccountUpdateMulti&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.account_.Destroy();
  this_._impl_.modelcode_.Destroy();
  this_._impl_.key_.Destroy();
  this_._impl_.value_.Destroy();
  this_._impl_.currency_.Destroy();
  this_._impl_.~Impl_();
}

inline void* AccountUpdateMulti::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AccountUpdateMulti(arena);
}
constexpr auto AccountUpdateMulti::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AccountUpdateMulti),
                                            alignof(AccountUpdateMulti));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AccountUpdateMulti::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AccountUpdateMulti_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AccountUpdateMulti::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<AccountUpdateMulti>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AccountUpdateMulti::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<AccountUpdateMulti>(), &AccountUpdateMulti::ByteSizeLong,
            &AccountUpdateMulti::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_._cached_size_),
        false,
    },
    &AccountUpdateMulti::kDescriptorMethods,
    &descriptor_table_AccountUpdateMulti_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AccountUpdateMulti::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 68, 2> AccountUpdateMulti::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::AccountUpdateMulti>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 reqId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AccountUpdateMulti, _impl_.reqid_), 5>(),
     {8, 5, 0, PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_.reqid_)}},
    // optional string account = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_.account_)}},
    // optional string modelCode = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_.modelcode_)}},
    // optional string key = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 2, 0, PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_.key_)}},
    // optional string value = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 3, 0, PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_.value_)}},
    // optional string currency = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 4, 0, PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_.currency_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 reqId = 1;
    {PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_.reqid_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string account = 2;
    {PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_.account_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string modelCode = 3;
    {PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_.modelcode_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string key = 4;
    {PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_.key_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string value = 5;
    {PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_.value_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string currency = 6;
    {PROTOBUF_FIELD_OFFSET(AccountUpdateMulti, _impl_.currency_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\33\0\7\11\3\5\10\0"
    "protobuf.AccountUpdateMulti"
    "account"
    "modelCode"
    "key"
    "value"
    "currency"
  }},
};

PROTOBUF_NOINLINE void AccountUpdateMulti::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.AccountUpdateMulti)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.account_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.modelcode_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.key_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.value_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      _impl_.currency_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.reqid_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AccountUpdateMulti::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AccountUpdateMulti& this_ = static_cast<const AccountUpdateMulti&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AccountUpdateMulti::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AccountUpdateMulti& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protobuf.AccountUpdateMulti)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 reqId = 1;
          if (cached_has_bits & 0x00000020u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_reqid(), target);
          }

          // optional string account = 2;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_account();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.AccountUpdateMulti.account");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // optional string modelCode = 3;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_modelcode();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.AccountUpdateMulti.modelCode");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // optional string key = 4;
          if (cached_has_bits & 0x00000004u) {
            const std::string& _s = this_._internal_key();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.AccountUpdateMulti.key");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // optional string value = 5;
          if (cached_has_bits & 0x00000008u) {
            const std::string& _s = this_._internal_value();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.AccountUpdateMulti.value");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          // optional string currency = 6;
          if (cached_has_bits & 0x00000010u) {
            const std::string& _s = this_._internal_currency();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.AccountUpdateMulti.currency");
            target = stream->WriteStringMaybeAliased(6, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protobuf.AccountUpdateMulti)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AccountUpdateMulti::ByteSizeLong(const MessageLite& base) {
          const AccountUpdateMulti& this_ = static_cast<const AccountUpdateMulti&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AccountUpdateMulti::ByteSizeLong() const {
          const AccountUpdateMulti& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protobuf.AccountUpdateMulti)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x0000003fu) {
            // optional string account = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_account());
            }
            // optional string modelCode = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_modelcode());
            }
            // optional string key = 4;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_key());
            }
            // optional string value = 5;
            if (cached_has_bits & 0x00000008u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_value());
            }
            // optional string currency = 6;
            if (cached_has_bits & 0x00000010u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_currency());
            }
            // optional int32 reqId = 1;
            if (cached_has_bits & 0x00000020u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_reqid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AccountUpdateMulti::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AccountUpdateMulti*>(&to_msg);
  auto& from = static_cast<const AccountUpdateMulti&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.AccountUpdateMulti)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_account(from._internal_account());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_modelcode(from._internal_modelcode());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_key(from._internal_key());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_value(from._internal_value());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_set_currency(from._internal_currency());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.reqid_ = from._impl_.reqid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AccountUpdateMulti::CopyFrom(const AccountUpdateMulti& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.AccountUpdateMulti)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AccountUpdateMulti::InternalSwap(AccountUpdateMulti* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_, &other->_impl_.account_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.modelcode_, &other->_impl_.modelcode_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.currency_, &other->_impl_.currency_, arena);
        swap(_impl_.reqid_, other->_impl_.reqid_);
}

::google::protobuf::Metadata AccountUpdateMulti::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_AccountUpdateMulti_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
