// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AccountDataRequest.proto
// Protobuf C++ Version: 5.29.3

#ifndef AccountDataRequest_2eproto_2epb_2eh
#define AccountDataRequest_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_AccountDataRequest_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_AccountDataRequest_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_AccountDataRequest_2eproto;
namespace protobuf {
class AccountDataRequest;
struct AccountDataRequestDefaultTypeInternal;
extern AccountDataRequestDefaultTypeInternal _AccountDataRequest_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class AccountDataRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.AccountDataRequest) */ {
 public:
  inline AccountDataRequest() : AccountDataRequest(nullptr) {}
  ~AccountDataRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AccountDataRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AccountDataRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AccountDataRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline AccountDataRequest(const AccountDataRequest& from) : AccountDataRequest(nullptr, from) {}
  inline AccountDataRequest(AccountDataRequest&& from) noexcept
      : AccountDataRequest(nullptr, std::move(from)) {}
  inline AccountDataRequest& operator=(const AccountDataRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountDataRequest& operator=(AccountDataRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AccountDataRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AccountDataRequest* internal_default_instance() {
    return reinterpret_cast<const AccountDataRequest*>(
        &_AccountDataRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AccountDataRequest& a, AccountDataRequest& b) { a.Swap(&b); }
  inline void Swap(AccountDataRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountDataRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AccountDataRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AccountDataRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AccountDataRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AccountDataRequest& from) { AccountDataRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AccountDataRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.AccountDataRequest"; }

 protected:
  explicit AccountDataRequest(::google::protobuf::Arena* arena);
  AccountDataRequest(::google::protobuf::Arena* arena, const AccountDataRequest& from);
  AccountDataRequest(::google::protobuf::Arena* arena, AccountDataRequest&& from) noexcept
      : AccountDataRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAcctCodeFieldNumber = 2,
    kSubscribeFieldNumber = 1,
  };
  // optional string acctCode = 2;
  bool has_acctcode() const;
  void clear_acctcode() ;
  const std::string& acctcode() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_acctcode(Arg_&& arg, Args_... args);
  std::string* mutable_acctcode();
  PROTOBUF_NODISCARD std::string* release_acctcode();
  void set_allocated_acctcode(std::string* value);

  private:
  const std::string& _internal_acctcode() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_acctcode(
      const std::string& value);
  std::string* _internal_mutable_acctcode();

  public:
  // optional bool subscribe = 1;
  bool has_subscribe() const;
  void clear_subscribe() ;
  bool subscribe() const;
  void set_subscribe(bool value);

  private:
  bool _internal_subscribe() const;
  void _internal_set_subscribe(bool value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.AccountDataRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      44, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AccountDataRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr acctcode_;
    bool subscribe_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AccountDataRequest_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AccountDataRequest

// optional bool subscribe = 1;
inline bool AccountDataRequest::has_subscribe() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void AccountDataRequest::clear_subscribe() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.subscribe_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool AccountDataRequest::subscribe() const {
  // @@protoc_insertion_point(field_get:protobuf.AccountDataRequest.subscribe)
  return _internal_subscribe();
}
inline void AccountDataRequest::set_subscribe(bool value) {
  _internal_set_subscribe(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:protobuf.AccountDataRequest.subscribe)
}
inline bool AccountDataRequest::_internal_subscribe() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.subscribe_;
}
inline void AccountDataRequest::_internal_set_subscribe(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.subscribe_ = value;
}

// optional string acctCode = 2;
inline bool AccountDataRequest::has_acctcode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void AccountDataRequest::clear_acctcode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.acctcode_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& AccountDataRequest::acctcode() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.AccountDataRequest.acctCode)
  return _internal_acctcode();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AccountDataRequest::set_acctcode(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.acctcode_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.AccountDataRequest.acctCode)
}
inline std::string* AccountDataRequest::mutable_acctcode() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_acctcode();
  // @@protoc_insertion_point(field_mutable:protobuf.AccountDataRequest.acctCode)
  return _s;
}
inline const std::string& AccountDataRequest::_internal_acctcode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.acctcode_.Get();
}
inline void AccountDataRequest::_internal_set_acctcode(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.acctcode_.Set(value, GetArena());
}
inline std::string* AccountDataRequest::_internal_mutable_acctcode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.acctcode_.Mutable( GetArena());
}
inline std::string* AccountDataRequest::release_acctcode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.AccountDataRequest.acctCode)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.acctcode_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.acctcode_.Set("", GetArena());
  }
  return released;
}
inline void AccountDataRequest::set_allocated_acctcode(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.acctcode_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.acctcode_.IsDefault()) {
    _impl_.acctcode_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.AccountDataRequest.acctCode)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // AccountDataRequest_2eproto_2epb_2eh
