// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: CompletedOrdersEnd.proto
// Protobuf C++ Version: 5.29.3

#include "CompletedOrdersEnd.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {
              template <typename>
PROTOBUF_CONSTEXPR CompletedOrdersEnd::CompletedOrdersEnd(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct CompletedOrdersEndDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CompletedOrdersEndDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CompletedOrdersEndDefaultTypeInternal() {}
  union {
    CompletedOrdersEnd _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CompletedOrdersEndDefaultTypeInternal _CompletedOrdersEnd_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_CompletedOrdersEnd_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_CompletedOrdersEnd_2eproto = nullptr;
const ::uint32_t
    TableStruct_CompletedOrdersEnd_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::protobuf::CompletedOrdersEnd, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::protobuf::CompletedOrdersEnd)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_CompletedOrdersEnd_default_instance_._instance,
};
const char descriptor_table_protodef_CompletedOrdersEnd_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030CompletedOrdersEnd.proto\022\010protobuf\"\024\n\022"
    "CompletedOrdersEndBB\n\026com.ib.client.prot"
    "obufB\027CompletedOrdersEndProto\252\002\016IBApi.pr"
    "otobufb\006proto3"
};
static ::absl::once_flag descriptor_table_CompletedOrdersEnd_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_CompletedOrdersEnd_2eproto = {
    false,
    false,
    134,
    descriptor_table_protodef_CompletedOrdersEnd_2eproto,
    "CompletedOrdersEnd.proto",
    &descriptor_table_CompletedOrdersEnd_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_CompletedOrdersEnd_2eproto::offsets,
    file_level_enum_descriptors_CompletedOrdersEnd_2eproto,
    file_level_service_descriptors_CompletedOrdersEnd_2eproto,
};
namespace protobuf {
// ===================================================================

class CompletedOrdersEnd::_Internal {
 public:
};

CompletedOrdersEnd::CompletedOrdersEnd(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:protobuf.CompletedOrdersEnd)
}
CompletedOrdersEnd::CompletedOrdersEnd(
    ::google::protobuf::Arena* arena,
    const CompletedOrdersEnd& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CompletedOrdersEnd* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:protobuf.CompletedOrdersEnd)
}

inline void* CompletedOrdersEnd::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CompletedOrdersEnd(arena);
}
constexpr auto CompletedOrdersEnd::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CompletedOrdersEnd),
                                            alignof(CompletedOrdersEnd));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CompletedOrdersEnd::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CompletedOrdersEnd_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CompletedOrdersEnd::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<CompletedOrdersEnd>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CompletedOrdersEnd::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<CompletedOrdersEnd>(), &CompletedOrdersEnd::ByteSizeLong,
            &CompletedOrdersEnd::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CompletedOrdersEnd, _impl_._cached_size_),
        false,
    },
    &CompletedOrdersEnd::kDescriptorMethods,
    &descriptor_table_CompletedOrdersEnd_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CompletedOrdersEnd::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> CompletedOrdersEnd::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::CompletedOrdersEnd>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata CompletedOrdersEnd::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_CompletedOrdersEnd_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
