// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ContractData.proto
// Protobuf C++ Version: 5.29.3

#ifndef ContractData_2eproto_2epb_2eh
#define ContractData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "Contract.pb.h"
#include "ContractDetails.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ContractData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ContractData_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ContractData_2eproto;
namespace protobuf {
class ContractData;
struct ContractDataDefaultTypeInternal;
extern ContractDataDefaultTypeInternal _ContractData_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class ContractData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.ContractData) */ {
 public:
  inline ContractData() : ContractData(nullptr) {}
  ~ContractData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ContractData* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ContractData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ContractData(
      ::google::protobuf::internal::ConstantInitialized);

  inline ContractData(const ContractData& from) : ContractData(nullptr, from) {}
  inline ContractData(ContractData&& from) noexcept
      : ContractData(nullptr, std::move(from)) {}
  inline ContractData& operator=(const ContractData& from) {
    CopyFrom(from);
    return *this;
  }
  inline ContractData& operator=(ContractData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ContractData& default_instance() {
    return *internal_default_instance();
  }
  static inline const ContractData* internal_default_instance() {
    return reinterpret_cast<const ContractData*>(
        &_ContractData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ContractData& a, ContractData& b) { a.Swap(&b); }
  inline void Swap(ContractData* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ContractData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ContractData* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ContractData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ContractData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ContractData& from) { ContractData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ContractData* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.ContractData"; }

 protected:
  explicit ContractData(::google::protobuf::Arena* arena);
  ContractData(::google::protobuf::Arena* arena, const ContractData& from);
  ContractData(::google::protobuf::Arena* arena, ContractData&& from) noexcept
      : ContractData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kContractFieldNumber = 2,
    kContractDetailsFieldNumber = 3,
    kReqIdFieldNumber = 1,
  };
  // optional .protobuf.Contract contract = 2;
  bool has_contract() const;
  void clear_contract() ;
  const ::protobuf::Contract& contract() const;
  PROTOBUF_NODISCARD ::protobuf::Contract* release_contract();
  ::protobuf::Contract* mutable_contract();
  void set_allocated_contract(::protobuf::Contract* value);
  void unsafe_arena_set_allocated_contract(::protobuf::Contract* value);
  ::protobuf::Contract* unsafe_arena_release_contract();

  private:
  const ::protobuf::Contract& _internal_contract() const;
  ::protobuf::Contract* _internal_mutable_contract();

  public:
  // optional .protobuf.ContractDetails contractDetails = 3;
  bool has_contractdetails() const;
  void clear_contractdetails() ;
  const ::protobuf::ContractDetails& contractdetails() const;
  PROTOBUF_NODISCARD ::protobuf::ContractDetails* release_contractdetails();
  ::protobuf::ContractDetails* mutable_contractdetails();
  void set_allocated_contractdetails(::protobuf::ContractDetails* value);
  void unsafe_arena_set_allocated_contractdetails(::protobuf::ContractDetails* value);
  ::protobuf::ContractDetails* unsafe_arena_release_contractdetails();

  private:
  const ::protobuf::ContractDetails& _internal_contractdetails() const;
  ::protobuf::ContractDetails* _internal_mutable_contractdetails();

  public:
  // optional int32 reqId = 1;
  bool has_reqid() const;
  void clear_reqid() ;
  ::int32_t reqid() const;
  void set_reqid(::int32_t value);

  private:
  ::int32_t _internal_reqid() const;
  void _internal_set_reqid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.ContractData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ContractData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::protobuf::Contract* contract_;
    ::protobuf::ContractDetails* contractdetails_;
    ::int32_t reqid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ContractData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ContractData

// optional int32 reqId = 1;
inline bool ContractData::has_reqid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ContractData::clear_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t ContractData::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.ContractData.reqId)
  return _internal_reqid();
}
inline void ContractData::set_reqid(::int32_t value) {
  _internal_set_reqid(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:protobuf.ContractData.reqId)
}
inline ::int32_t ContractData::_internal_reqid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reqid_;
}
inline void ContractData::_internal_set_reqid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = value;
}

// optional .protobuf.Contract contract = 2;
inline bool ContractData::has_contract() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.contract_ != nullptr);
  return value;
}
inline const ::protobuf::Contract& ContractData::_internal_contract() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::protobuf::Contract* p = _impl_.contract_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::Contract&>(::protobuf::_Contract_default_instance_);
}
inline const ::protobuf::Contract& ContractData::contract() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ContractData.contract)
  return _internal_contract();
}
inline void ContractData::unsafe_arena_set_allocated_contract(::protobuf::Contract* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.contract_);
  }
  _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.ContractData.contract)
}
inline ::protobuf::Contract* ContractData::release_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::protobuf::Contract* released = _impl_.contract_;
  _impl_.contract_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::protobuf::Contract* ContractData::unsafe_arena_release_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ContractData.contract)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::protobuf::Contract* temp = _impl_.contract_;
  _impl_.contract_ = nullptr;
  return temp;
}
inline ::protobuf::Contract* ContractData::_internal_mutable_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.contract_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::protobuf::Contract>(GetArena());
    _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(p);
  }
  return _impl_.contract_;
}
inline ::protobuf::Contract* ContractData::mutable_contract() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::protobuf::Contract* _msg = _internal_mutable_contract();
  // @@protoc_insertion_point(field_mutable:protobuf.ContractData.contract)
  return _msg;
}
inline void ContractData::set_allocated_contract(::protobuf::Contract* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.contract_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(value);
  // @@protoc_insertion_point(field_set_allocated:protobuf.ContractData.contract)
}

// optional .protobuf.ContractDetails contractDetails = 3;
inline bool ContractData::has_contractdetails() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.contractdetails_ != nullptr);
  return value;
}
inline const ::protobuf::ContractDetails& ContractData::_internal_contractdetails() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::protobuf::ContractDetails* p = _impl_.contractdetails_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::ContractDetails&>(::protobuf::_ContractDetails_default_instance_);
}
inline const ::protobuf::ContractDetails& ContractData::contractdetails() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.ContractData.contractDetails)
  return _internal_contractdetails();
}
inline void ContractData::unsafe_arena_set_allocated_contractdetails(::protobuf::ContractDetails* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.contractdetails_);
  }
  _impl_.contractdetails_ = reinterpret_cast<::protobuf::ContractDetails*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.ContractData.contractDetails)
}
inline ::protobuf::ContractDetails* ContractData::release_contractdetails() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::protobuf::ContractDetails* released = _impl_.contractdetails_;
  _impl_.contractdetails_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::protobuf::ContractDetails* ContractData::unsafe_arena_release_contractdetails() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.ContractData.contractDetails)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::protobuf::ContractDetails* temp = _impl_.contractdetails_;
  _impl_.contractdetails_ = nullptr;
  return temp;
}
inline ::protobuf::ContractDetails* ContractData::_internal_mutable_contractdetails() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.contractdetails_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::protobuf::ContractDetails>(GetArena());
    _impl_.contractdetails_ = reinterpret_cast<::protobuf::ContractDetails*>(p);
  }
  return _impl_.contractdetails_;
}
inline ::protobuf::ContractDetails* ContractData::mutable_contractdetails() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::protobuf::ContractDetails* _msg = _internal_mutable_contractdetails();
  // @@protoc_insertion_point(field_mutable:protobuf.ContractData.contractDetails)
  return _msg;
}
inline void ContractData::set_allocated_contractdetails(::protobuf::ContractDetails* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.contractdetails_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.contractdetails_ = reinterpret_cast<::protobuf::ContractDetails*>(value);
  // @@protoc_insertion_point(field_set_allocated:protobuf.ContractData.contractDetails)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ContractData_2eproto_2epb_2eh
