// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: HistogramDataRequest.proto
// Protobuf C++ Version: 5.29.3

#ifndef HistogramDataRequest_2eproto_2epb_2eh
#define HistogramDataRequest_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "Contract.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_HistogramDataRequest_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_HistogramDataRequest_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_HistogramDataRequest_2eproto;
namespace protobuf {
class HistogramDataRequest;
struct HistogramDataRequestDefaultTypeInternal;
extern HistogramDataRequestDefaultTypeInternal _HistogramDataRequest_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class HistogramDataRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.HistogramDataRequest) */ {
 public:
  inline HistogramDataRequest() : HistogramDataRequest(nullptr) {}
  ~HistogramDataRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HistogramDataRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HistogramDataRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HistogramDataRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline HistogramDataRequest(const HistogramDataRequest& from) : HistogramDataRequest(nullptr, from) {}
  inline HistogramDataRequest(HistogramDataRequest&& from) noexcept
      : HistogramDataRequest(nullptr, std::move(from)) {}
  inline HistogramDataRequest& operator=(const HistogramDataRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HistogramDataRequest& operator=(HistogramDataRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HistogramDataRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HistogramDataRequest* internal_default_instance() {
    return reinterpret_cast<const HistogramDataRequest*>(
        &_HistogramDataRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(HistogramDataRequest& a, HistogramDataRequest& b) { a.Swap(&b); }
  inline void Swap(HistogramDataRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HistogramDataRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HistogramDataRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HistogramDataRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HistogramDataRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HistogramDataRequest& from) { HistogramDataRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HistogramDataRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.HistogramDataRequest"; }

 protected:
  explicit HistogramDataRequest(::google::protobuf::Arena* arena);
  HistogramDataRequest(::google::protobuf::Arena* arena, const HistogramDataRequest& from);
  HistogramDataRequest(::google::protobuf::Arena* arena, HistogramDataRequest&& from) noexcept
      : HistogramDataRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimePeriodFieldNumber = 4,
    kContractFieldNumber = 2,
    kReqIdFieldNumber = 1,
    kUseRTHFieldNumber = 3,
  };
  // optional string timePeriod = 4;
  bool has_timeperiod() const;
  void clear_timeperiod() ;
  const std::string& timeperiod() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_timeperiod(Arg_&& arg, Args_... args);
  std::string* mutable_timeperiod();
  PROTOBUF_NODISCARD std::string* release_timeperiod();
  void set_allocated_timeperiod(std::string* value);

  private:
  const std::string& _internal_timeperiod() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timeperiod(
      const std::string& value);
  std::string* _internal_mutable_timeperiod();

  public:
  // optional .protobuf.Contract contract = 2;
  bool has_contract() const;
  void clear_contract() ;
  const ::protobuf::Contract& contract() const;
  PROTOBUF_NODISCARD ::protobuf::Contract* release_contract();
  ::protobuf::Contract* mutable_contract();
  void set_allocated_contract(::protobuf::Contract* value);
  void unsafe_arena_set_allocated_contract(::protobuf::Contract* value);
  ::protobuf::Contract* unsafe_arena_release_contract();

  private:
  const ::protobuf::Contract& _internal_contract() const;
  ::protobuf::Contract* _internal_mutable_contract();

  public:
  // optional int32 reqId = 1;
  bool has_reqid() const;
  void clear_reqid() ;
  ::int32_t reqid() const;
  void set_reqid(::int32_t value);

  private:
  ::int32_t _internal_reqid() const;
  void _internal_set_reqid(::int32_t value);

  public:
  // optional bool useRTH = 3;
  bool has_userth() const;
  void clear_userth() ;
  bool userth() const;
  void set_userth(bool value);

  private:
  bool _internal_userth() const;
  void _internal_set_userth(bool value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.HistogramDataRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 1,
      48, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const HistogramDataRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr timeperiod_;
    ::protobuf::Contract* contract_;
    ::int32_t reqid_;
    bool userth_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HistogramDataRequest_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// HistogramDataRequest

// optional int32 reqId = 1;
inline bool HistogramDataRequest::has_reqid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void HistogramDataRequest::clear_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t HistogramDataRequest::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.HistogramDataRequest.reqId)
  return _internal_reqid();
}
inline void HistogramDataRequest::set_reqid(::int32_t value) {
  _internal_set_reqid(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:protobuf.HistogramDataRequest.reqId)
}
inline ::int32_t HistogramDataRequest::_internal_reqid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reqid_;
}
inline void HistogramDataRequest::_internal_set_reqid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = value;
}

// optional .protobuf.Contract contract = 2;
inline bool HistogramDataRequest::has_contract() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.contract_ != nullptr);
  return value;
}
inline const ::protobuf::Contract& HistogramDataRequest::_internal_contract() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::protobuf::Contract* p = _impl_.contract_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::Contract&>(::protobuf::_Contract_default_instance_);
}
inline const ::protobuf::Contract& HistogramDataRequest::contract() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.HistogramDataRequest.contract)
  return _internal_contract();
}
inline void HistogramDataRequest::unsafe_arena_set_allocated_contract(::protobuf::Contract* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.contract_);
  }
  _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.HistogramDataRequest.contract)
}
inline ::protobuf::Contract* HistogramDataRequest::release_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::protobuf::Contract* released = _impl_.contract_;
  _impl_.contract_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::protobuf::Contract* HistogramDataRequest::unsafe_arena_release_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.HistogramDataRequest.contract)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::protobuf::Contract* temp = _impl_.contract_;
  _impl_.contract_ = nullptr;
  return temp;
}
inline ::protobuf::Contract* HistogramDataRequest::_internal_mutable_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.contract_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::protobuf::Contract>(GetArena());
    _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(p);
  }
  return _impl_.contract_;
}
inline ::protobuf::Contract* HistogramDataRequest::mutable_contract() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::protobuf::Contract* _msg = _internal_mutable_contract();
  // @@protoc_insertion_point(field_mutable:protobuf.HistogramDataRequest.contract)
  return _msg;
}
inline void HistogramDataRequest::set_allocated_contract(::protobuf::Contract* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.contract_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(value);
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistogramDataRequest.contract)
}

// optional bool useRTH = 3;
inline bool HistogramDataRequest::has_userth() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void HistogramDataRequest::clear_userth() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userth_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool HistogramDataRequest::userth() const {
  // @@protoc_insertion_point(field_get:protobuf.HistogramDataRequest.useRTH)
  return _internal_userth();
}
inline void HistogramDataRequest::set_userth(bool value) {
  _internal_set_userth(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:protobuf.HistogramDataRequest.useRTH)
}
inline bool HistogramDataRequest::_internal_userth() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.userth_;
}
inline void HistogramDataRequest::_internal_set_userth(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userth_ = value;
}

// optional string timePeriod = 4;
inline bool HistogramDataRequest::has_timeperiod() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void HistogramDataRequest::clear_timeperiod() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timeperiod_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& HistogramDataRequest::timeperiod() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.HistogramDataRequest.timePeriod)
  return _internal_timeperiod();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HistogramDataRequest::set_timeperiod(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.timeperiod_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.HistogramDataRequest.timePeriod)
}
inline std::string* HistogramDataRequest::mutable_timeperiod() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_timeperiod();
  // @@protoc_insertion_point(field_mutable:protobuf.HistogramDataRequest.timePeriod)
  return _s;
}
inline const std::string& HistogramDataRequest::_internal_timeperiod() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timeperiod_.Get();
}
inline void HistogramDataRequest::_internal_set_timeperiod(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.timeperiod_.Set(value, GetArena());
}
inline std::string* HistogramDataRequest::_internal_mutable_timeperiod() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.timeperiod_.Mutable( GetArena());
}
inline std::string* HistogramDataRequest::release_timeperiod() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.HistogramDataRequest.timePeriod)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.timeperiod_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.timeperiod_.Set("", GetArena());
  }
  return released;
}
inline void HistogramDataRequest::set_allocated_timeperiod(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.timeperiod_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.timeperiod_.IsDefault()) {
    _impl_.timeperiod_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistogramDataRequest.timePeriod)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // HistogramDataRequest_2eproto_2epb_2eh
