// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: HistoricalDataRequest.proto
// Protobuf C++ Version: 5.29.3

#ifndef HistoricalDataRequest_2eproto_2epb_2eh
#define HistoricalDataRequest_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
#include "Contract.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_HistoricalDataRequest_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_HistoricalDataRequest_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_HistoricalDataRequest_2eproto;
namespace protobuf {
class HistoricalDataRequest;
struct HistoricalDataRequestDefaultTypeInternal;
extern HistoricalDataRequestDefaultTypeInternal _HistoricalDataRequest_default_instance_;
class HistoricalDataRequest_ChartOptionsEntry_DoNotUse;
struct HistoricalDataRequest_ChartOptionsEntry_DoNotUseDefaultTypeInternal;
extern HistoricalDataRequest_ChartOptionsEntry_DoNotUseDefaultTypeInternal _HistoricalDataRequest_ChartOptionsEntry_DoNotUse_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class HistoricalDataRequest_ChartOptionsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  HistoricalDataRequest_ChartOptionsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HistoricalDataRequest_ChartOptionsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit HistoricalDataRequest_ChartOptionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const HistoricalDataRequest_ChartOptionsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const HistoricalDataRequest_ChartOptionsEntry_DoNotUse*>(
        &_HistoricalDataRequest_ChartOptionsEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_HistoricalDataRequest_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      65, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class HistoricalDataRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.HistoricalDataRequest) */ {
 public:
  inline HistoricalDataRequest() : HistoricalDataRequest(nullptr) {}
  ~HistoricalDataRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HistoricalDataRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HistoricalDataRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HistoricalDataRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline HistoricalDataRequest(const HistoricalDataRequest& from) : HistoricalDataRequest(nullptr, from) {}
  inline HistoricalDataRequest(HistoricalDataRequest&& from) noexcept
      : HistoricalDataRequest(nullptr, std::move(from)) {}
  inline HistoricalDataRequest& operator=(const HistoricalDataRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline HistoricalDataRequest& operator=(HistoricalDataRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HistoricalDataRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const HistoricalDataRequest* internal_default_instance() {
    return reinterpret_cast<const HistoricalDataRequest*>(
        &_HistoricalDataRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(HistoricalDataRequest& a, HistoricalDataRequest& b) { a.Swap(&b); }
  inline void Swap(HistoricalDataRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HistoricalDataRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HistoricalDataRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HistoricalDataRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HistoricalDataRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HistoricalDataRequest& from) { HistoricalDataRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HistoricalDataRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.HistoricalDataRequest"; }

 protected:
  explicit HistoricalDataRequest(::google::protobuf::Arena* arena);
  HistoricalDataRequest(::google::protobuf::Arena* arena, const HistoricalDataRequest& from);
  HistoricalDataRequest(::google::protobuf::Arena* arena, HistoricalDataRequest&& from) noexcept
      : HistoricalDataRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kChartOptionsFieldNumber = 10,
    kEndDateTimeFieldNumber = 3,
    kBarSizeSettingFieldNumber = 4,
    kDurationFieldNumber = 5,
    kWhatToShowFieldNumber = 7,
    kContractFieldNumber = 2,
    kReqIdFieldNumber = 1,
    kUseRTHFieldNumber = 6,
    kKeepUpToDateFieldNumber = 9,
    kFormatDateFieldNumber = 8,
  };
  // map<string, string> chartOptions = 10;
  int chartoptions_size() const;
  private:
  int _internal_chartoptions_size() const;

  public:
  void clear_chartoptions() ;
  const ::google::protobuf::Map<std::string, std::string>& chartoptions() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_chartoptions();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_chartoptions() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_chartoptions();

  public:
  // optional string endDateTime = 3;
  bool has_enddatetime() const;
  void clear_enddatetime() ;
  const std::string& enddatetime() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_enddatetime(Arg_&& arg, Args_... args);
  std::string* mutable_enddatetime();
  PROTOBUF_NODISCARD std::string* release_enddatetime();
  void set_allocated_enddatetime(std::string* value);

  private:
  const std::string& _internal_enddatetime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_enddatetime(
      const std::string& value);
  std::string* _internal_mutable_enddatetime();

  public:
  // optional string barSizeSetting = 4;
  bool has_barsizesetting() const;
  void clear_barsizesetting() ;
  const std::string& barsizesetting() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_barsizesetting(Arg_&& arg, Args_... args);
  std::string* mutable_barsizesetting();
  PROTOBUF_NODISCARD std::string* release_barsizesetting();
  void set_allocated_barsizesetting(std::string* value);

  private:
  const std::string& _internal_barsizesetting() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_barsizesetting(
      const std::string& value);
  std::string* _internal_mutable_barsizesetting();

  public:
  // optional string duration = 5;
  bool has_duration() const;
  void clear_duration() ;
  const std::string& duration() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_duration(Arg_&& arg, Args_... args);
  std::string* mutable_duration();
  PROTOBUF_NODISCARD std::string* release_duration();
  void set_allocated_duration(std::string* value);

  private:
  const std::string& _internal_duration() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_duration(
      const std::string& value);
  std::string* _internal_mutable_duration();

  public:
  // optional string whatToShow = 7;
  bool has_whattoshow() const;
  void clear_whattoshow() ;
  const std::string& whattoshow() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_whattoshow(Arg_&& arg, Args_... args);
  std::string* mutable_whattoshow();
  PROTOBUF_NODISCARD std::string* release_whattoshow();
  void set_allocated_whattoshow(std::string* value);

  private:
  const std::string& _internal_whattoshow() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_whattoshow(
      const std::string& value);
  std::string* _internal_mutable_whattoshow();

  public:
  // optional .protobuf.Contract contract = 2;
  bool has_contract() const;
  void clear_contract() ;
  const ::protobuf::Contract& contract() const;
  PROTOBUF_NODISCARD ::protobuf::Contract* release_contract();
  ::protobuf::Contract* mutable_contract();
  void set_allocated_contract(::protobuf::Contract* value);
  void unsafe_arena_set_allocated_contract(::protobuf::Contract* value);
  ::protobuf::Contract* unsafe_arena_release_contract();

  private:
  const ::protobuf::Contract& _internal_contract() const;
  ::protobuf::Contract* _internal_mutable_contract();

  public:
  // optional int32 reqId = 1;
  bool has_reqid() const;
  void clear_reqid() ;
  ::int32_t reqid() const;
  void set_reqid(::int32_t value);

  private:
  ::int32_t _internal_reqid() const;
  void _internal_set_reqid(::int32_t value);

  public:
  // optional bool useRTH = 6;
  bool has_userth() const;
  void clear_userth() ;
  bool userth() const;
  void set_userth(bool value);

  private:
  bool _internal_userth() const;
  void _internal_set_userth(bool value);

  public:
  // optional bool keepUpToDate = 9;
  bool has_keepuptodate() const;
  void clear_keepuptodate() ;
  bool keepuptodate() const;
  void set_keepuptodate(bool value);

  private:
  bool _internal_keepuptodate() const;
  void _internal_set_keepuptodate(bool value);

  public:
  // optional int32 formatDate = 8;
  bool has_formatdate() const;
  void clear_formatdate() ;
  ::int32_t formatdate() const;
  void set_formatdate(::int32_t value);

  private:
  ::int32_t _internal_formatdate() const;
  void _internal_set_formatdate(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.HistoricalDataRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 10, 2,
      102, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const HistoricalDataRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapField<HistoricalDataRequest_ChartOptionsEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        chartoptions_;
    ::google::protobuf::internal::ArenaStringPtr enddatetime_;
    ::google::protobuf::internal::ArenaStringPtr barsizesetting_;
    ::google::protobuf::internal::ArenaStringPtr duration_;
    ::google::protobuf::internal::ArenaStringPtr whattoshow_;
    ::protobuf::Contract* contract_;
    ::int32_t reqid_;
    bool userth_;
    bool keepuptodate_;
    ::int32_t formatdate_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HistoricalDataRequest_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// HistoricalDataRequest

// optional int32 reqId = 1;
inline bool HistoricalDataRequest::has_reqid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void HistoricalDataRequest::clear_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t HistoricalDataRequest::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalDataRequest.reqId)
  return _internal_reqid();
}
inline void HistoricalDataRequest::set_reqid(::int32_t value) {
  _internal_set_reqid(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:protobuf.HistoricalDataRequest.reqId)
}
inline ::int32_t HistoricalDataRequest::_internal_reqid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reqid_;
}
inline void HistoricalDataRequest::_internal_set_reqid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = value;
}

// optional .protobuf.Contract contract = 2;
inline bool HistoricalDataRequest::has_contract() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.contract_ != nullptr);
  return value;
}
inline const ::protobuf::Contract& HistoricalDataRequest::_internal_contract() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::protobuf::Contract* p = _impl_.contract_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::Contract&>(::protobuf::_Contract_default_instance_);
}
inline const ::protobuf::Contract& HistoricalDataRequest::contract() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalDataRequest.contract)
  return _internal_contract();
}
inline void HistoricalDataRequest::unsafe_arena_set_allocated_contract(::protobuf::Contract* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.contract_);
  }
  _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.HistoricalDataRequest.contract)
}
inline ::protobuf::Contract* HistoricalDataRequest::release_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::protobuf::Contract* released = _impl_.contract_;
  _impl_.contract_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::protobuf::Contract* HistoricalDataRequest::unsafe_arena_release_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.HistoricalDataRequest.contract)

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::protobuf::Contract* temp = _impl_.contract_;
  _impl_.contract_ = nullptr;
  return temp;
}
inline ::protobuf::Contract* HistoricalDataRequest::_internal_mutable_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.contract_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::protobuf::Contract>(GetArena());
    _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(p);
  }
  return _impl_.contract_;
}
inline ::protobuf::Contract* HistoricalDataRequest::mutable_contract() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000010u;
  ::protobuf::Contract* _msg = _internal_mutable_contract();
  // @@protoc_insertion_point(field_mutable:protobuf.HistoricalDataRequest.contract)
  return _msg;
}
inline void HistoricalDataRequest::set_allocated_contract(::protobuf::Contract* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.contract_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }

  _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(value);
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistoricalDataRequest.contract)
}

// optional string endDateTime = 3;
inline bool HistoricalDataRequest::has_enddatetime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void HistoricalDataRequest::clear_enddatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enddatetime_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& HistoricalDataRequest::enddatetime() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalDataRequest.endDateTime)
  return _internal_enddatetime();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HistoricalDataRequest::set_enddatetime(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.enddatetime_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.HistoricalDataRequest.endDateTime)
}
inline std::string* HistoricalDataRequest::mutable_enddatetime() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_enddatetime();
  // @@protoc_insertion_point(field_mutable:protobuf.HistoricalDataRequest.endDateTime)
  return _s;
}
inline const std::string& HistoricalDataRequest::_internal_enddatetime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enddatetime_.Get();
}
inline void HistoricalDataRequest::_internal_set_enddatetime(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.enddatetime_.Set(value, GetArena());
}
inline std::string* HistoricalDataRequest::_internal_mutable_enddatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.enddatetime_.Mutable( GetArena());
}
inline std::string* HistoricalDataRequest::release_enddatetime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.HistoricalDataRequest.endDateTime)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.enddatetime_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.enddatetime_.Set("", GetArena());
  }
  return released;
}
inline void HistoricalDataRequest::set_allocated_enddatetime(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.enddatetime_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.enddatetime_.IsDefault()) {
    _impl_.enddatetime_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistoricalDataRequest.endDateTime)
}

// optional string barSizeSetting = 4;
inline bool HistoricalDataRequest::has_barsizesetting() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void HistoricalDataRequest::clear_barsizesetting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.barsizesetting_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& HistoricalDataRequest::barsizesetting() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalDataRequest.barSizeSetting)
  return _internal_barsizesetting();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HistoricalDataRequest::set_barsizesetting(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.barsizesetting_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.HistoricalDataRequest.barSizeSetting)
}
inline std::string* HistoricalDataRequest::mutable_barsizesetting() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_barsizesetting();
  // @@protoc_insertion_point(field_mutable:protobuf.HistoricalDataRequest.barSizeSetting)
  return _s;
}
inline const std::string& HistoricalDataRequest::_internal_barsizesetting() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.barsizesetting_.Get();
}
inline void HistoricalDataRequest::_internal_set_barsizesetting(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.barsizesetting_.Set(value, GetArena());
}
inline std::string* HistoricalDataRequest::_internal_mutable_barsizesetting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.barsizesetting_.Mutable( GetArena());
}
inline std::string* HistoricalDataRequest::release_barsizesetting() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.HistoricalDataRequest.barSizeSetting)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.barsizesetting_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.barsizesetting_.Set("", GetArena());
  }
  return released;
}
inline void HistoricalDataRequest::set_allocated_barsizesetting(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.barsizesetting_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.barsizesetting_.IsDefault()) {
    _impl_.barsizesetting_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistoricalDataRequest.barSizeSetting)
}

// optional string duration = 5;
inline bool HistoricalDataRequest::has_duration() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void HistoricalDataRequest::clear_duration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.duration_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& HistoricalDataRequest::duration() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalDataRequest.duration)
  return _internal_duration();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HistoricalDataRequest::set_duration(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.duration_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.HistoricalDataRequest.duration)
}
inline std::string* HistoricalDataRequest::mutable_duration() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_duration();
  // @@protoc_insertion_point(field_mutable:protobuf.HistoricalDataRequest.duration)
  return _s;
}
inline const std::string& HistoricalDataRequest::_internal_duration() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.duration_.Get();
}
inline void HistoricalDataRequest::_internal_set_duration(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.duration_.Set(value, GetArena());
}
inline std::string* HistoricalDataRequest::_internal_mutable_duration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.duration_.Mutable( GetArena());
}
inline std::string* HistoricalDataRequest::release_duration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.HistoricalDataRequest.duration)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.duration_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.duration_.Set("", GetArena());
  }
  return released;
}
inline void HistoricalDataRequest::set_allocated_duration(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.duration_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.duration_.IsDefault()) {
    _impl_.duration_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistoricalDataRequest.duration)
}

// optional bool useRTH = 6;
inline bool HistoricalDataRequest::has_userth() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void HistoricalDataRequest::clear_userth() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userth_ = false;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline bool HistoricalDataRequest::userth() const {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalDataRequest.useRTH)
  return _internal_userth();
}
inline void HistoricalDataRequest::set_userth(bool value) {
  _internal_set_userth(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:protobuf.HistoricalDataRequest.useRTH)
}
inline bool HistoricalDataRequest::_internal_userth() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.userth_;
}
inline void HistoricalDataRequest::_internal_set_userth(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userth_ = value;
}

// optional string whatToShow = 7;
inline bool HistoricalDataRequest::has_whattoshow() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void HistoricalDataRequest::clear_whattoshow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.whattoshow_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& HistoricalDataRequest::whattoshow() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalDataRequest.whatToShow)
  return _internal_whattoshow();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void HistoricalDataRequest::set_whattoshow(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.whattoshow_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.HistoricalDataRequest.whatToShow)
}
inline std::string* HistoricalDataRequest::mutable_whattoshow() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_whattoshow();
  // @@protoc_insertion_point(field_mutable:protobuf.HistoricalDataRequest.whatToShow)
  return _s;
}
inline const std::string& HistoricalDataRequest::_internal_whattoshow() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.whattoshow_.Get();
}
inline void HistoricalDataRequest::_internal_set_whattoshow(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.whattoshow_.Set(value, GetArena());
}
inline std::string* HistoricalDataRequest::_internal_mutable_whattoshow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.whattoshow_.Mutable( GetArena());
}
inline std::string* HistoricalDataRequest::release_whattoshow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.HistoricalDataRequest.whatToShow)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.whattoshow_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.whattoshow_.Set("", GetArena());
  }
  return released;
}
inline void HistoricalDataRequest::set_allocated_whattoshow(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.whattoshow_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.whattoshow_.IsDefault()) {
    _impl_.whattoshow_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.HistoricalDataRequest.whatToShow)
}

// optional int32 formatDate = 8;
inline bool HistoricalDataRequest::has_formatdate() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline void HistoricalDataRequest::clear_formatdate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.formatdate_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline ::int32_t HistoricalDataRequest::formatdate() const {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalDataRequest.formatDate)
  return _internal_formatdate();
}
inline void HistoricalDataRequest::set_formatdate(::int32_t value) {
  _internal_set_formatdate(value);
  _impl_._has_bits_[0] |= 0x00000100u;
  // @@protoc_insertion_point(field_set:protobuf.HistoricalDataRequest.formatDate)
}
inline ::int32_t HistoricalDataRequest::_internal_formatdate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.formatdate_;
}
inline void HistoricalDataRequest::_internal_set_formatdate(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.formatdate_ = value;
}

// optional bool keepUpToDate = 9;
inline bool HistoricalDataRequest::has_keepuptodate() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void HistoricalDataRequest::clear_keepuptodate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keepuptodate_ = false;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline bool HistoricalDataRequest::keepuptodate() const {
  // @@protoc_insertion_point(field_get:protobuf.HistoricalDataRequest.keepUpToDate)
  return _internal_keepuptodate();
}
inline void HistoricalDataRequest::set_keepuptodate(bool value) {
  _internal_set_keepuptodate(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:protobuf.HistoricalDataRequest.keepUpToDate)
}
inline bool HistoricalDataRequest::_internal_keepuptodate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.keepuptodate_;
}
inline void HistoricalDataRequest::_internal_set_keepuptodate(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keepuptodate_ = value;
}

// map<string, string> chartOptions = 10;
inline int HistoricalDataRequest::_internal_chartoptions_size() const {
  return _internal_chartoptions().size();
}
inline int HistoricalDataRequest::chartoptions_size() const {
  return _internal_chartoptions_size();
}
inline void HistoricalDataRequest::clear_chartoptions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chartoptions_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& HistoricalDataRequest::_internal_chartoptions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.chartoptions_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& HistoricalDataRequest::chartoptions() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:protobuf.HistoricalDataRequest.chartOptions)
  return _internal_chartoptions();
}
inline ::google::protobuf::Map<std::string, std::string>* HistoricalDataRequest::_internal_mutable_chartoptions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.chartoptions_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* HistoricalDataRequest::mutable_chartoptions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:protobuf.HistoricalDataRequest.chartOptions)
  return _internal_mutable_chartoptions();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // HistoricalDataRequest_2eproto_2epb_2eh
