// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: HistoricalTicksRequest.proto
// Protobuf C++ Version: 5.29.3

#include "HistoricalTicksRequest.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {
              template <typename>
PROTOBUF_CONSTEXPR HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::HistoricalTicksRequest_MiscOptionsEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct HistoricalTicksRequest_MiscOptionsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HistoricalTicksRequest_MiscOptionsEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HistoricalTicksRequest_MiscOptionsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    HistoricalTicksRequest_MiscOptionsEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HistoricalTicksRequest_MiscOptionsEntry_DoNotUseDefaultTypeInternal _HistoricalTicksRequest_MiscOptionsEntry_DoNotUse_default_instance_;

inline constexpr HistoricalTicksRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        miscoptions_{},
        startdatetime_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        enddatetime_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        whattoshow_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        contract_{nullptr},
        reqid_{0},
        numberofticks_{0},
        userth_{false},
        ignoresize_{false} {}

template <typename>
PROTOBUF_CONSTEXPR HistoricalTicksRequest::HistoricalTicksRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HistoricalTicksRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HistoricalTicksRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HistoricalTicksRequestDefaultTypeInternal() {}
  union {
    HistoricalTicksRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HistoricalTicksRequestDefaultTypeInternal _HistoricalTicksRequest_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_HistoricalTicksRequest_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_HistoricalTicksRequest_2eproto = nullptr;
const ::uint32_t
    TableStruct_HistoricalTicksRequest_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest_MiscOptionsEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest_MiscOptionsEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest_MiscOptionsEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest_MiscOptionsEntry_DoNotUse, _impl_.value_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest, _impl_.reqid_),
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest, _impl_.contract_),
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest, _impl_.startdatetime_),
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest, _impl_.enddatetime_),
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest, _impl_.numberofticks_),
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest, _impl_.whattoshow_),
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest, _impl_.userth_),
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest, _impl_.ignoresize_),
        PROTOBUF_FIELD_OFFSET(::protobuf::HistoricalTicksRequest, _impl_.miscoptions_),
        4,
        3,
        0,
        1,
        5,
        2,
        6,
        7,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::protobuf::HistoricalTicksRequest_MiscOptionsEntry_DoNotUse)},
        {12, 29, -1, sizeof(::protobuf::HistoricalTicksRequest)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_HistoricalTicksRequest_MiscOptionsEntry_DoNotUse_default_instance_._instance,
    &::protobuf::_HistoricalTicksRequest_default_instance_._instance,
};
const char descriptor_table_protodef_HistoricalTicksRequest_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\034HistoricalTicksRequest.proto\022\010protobuf"
    "\032\016Contract.proto\"\340\003\n\026HistoricalTicksRequ"
    "est\022\022\n\005reqId\030\001 \001(\005H\000\210\001\001\022)\n\010contract\030\002 \001("
    "\0132\022.protobuf.ContractH\001\210\001\001\022\032\n\rstartDateT"
    "ime\030\003 \001(\tH\002\210\001\001\022\030\n\013endDateTime\030\004 \001(\tH\003\210\001\001"
    "\022\032\n\rnumberOfTicks\030\005 \001(\005H\004\210\001\001\022\027\n\nwhatToSh"
    "ow\030\006 \001(\tH\005\210\001\001\022\023\n\006useRTH\030\007 \001(\010H\006\210\001\001\022\027\n\nig"
    "noreSize\030\010 \001(\010H\007\210\001\001\022F\n\013miscOptions\030\t \003(\013"
    "21.protobuf.HistoricalTicksRequest.MiscO"
    "ptionsEntry\0322\n\020MiscOptionsEntry\022\013\n\003key\030\001"
    " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\010\n\006_reqIdB\013\n\t_co"
    "ntractB\020\n\016_startDateTimeB\016\n\014_endDateTime"
    "B\020\n\016_numberOfTicksB\r\n\013_whatToShowB\t\n\007_us"
    "eRTHB\r\n\013_ignoreSizeBF\n\026com.ib.client.pro"
    "tobufB\033HistoricalTicksRequestProto\252\002\016IBA"
    "pi.protobufb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_HistoricalTicksRequest_2eproto_deps[1] =
    {
        &::descriptor_table_Contract_2eproto,
};
static ::absl::once_flag descriptor_table_HistoricalTicksRequest_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_HistoricalTicksRequest_2eproto = {
    false,
    false,
    619,
    descriptor_table_protodef_HistoricalTicksRequest_2eproto,
    "HistoricalTicksRequest.proto",
    &descriptor_table_HistoricalTicksRequest_2eproto_once,
    descriptor_table_HistoricalTicksRequest_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_HistoricalTicksRequest_2eproto::offsets,
    file_level_enum_descriptors_HistoricalTicksRequest_2eproto,
    file_level_service_descriptors_HistoricalTicksRequest_2eproto,
};
namespace protobuf {
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::HistoricalTicksRequest_MiscOptionsEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::HistoricalTicksRequest_MiscOptionsEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::HistoricalTicksRequest_MiscOptionsEntry_DoNotUse() : SuperType() {}
              HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::HistoricalTicksRequest_MiscOptionsEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) HistoricalTicksRequest_MiscOptionsEntry_DoNotUse(arena);
              }
              constexpr auto HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(HistoricalTicksRequest_MiscOptionsEntry_DoNotUse),
                                                          alignof(HistoricalTicksRequest_MiscOptionsEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_HistoricalTicksRequest_MiscOptionsEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<HistoricalTicksRequest_MiscOptionsEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest_MiscOptionsEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_HistoricalTicksRequest_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 65, 2> HistoricalTicksRequest_MiscOptionsEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest_MiscOptionsEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::HistoricalTicksRequest_MiscOptionsEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest_MiscOptionsEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest_MiscOptionsEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest_MiscOptionsEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest_MiscOptionsEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\60\3\5\0\0\0\0\0"
    "protobuf.HistoricalTicksRequest.MiscOptionsEntry"
    "key"
    "value"
  }},
};

// ===================================================================

class HistoricalTicksRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<HistoricalTicksRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_._has_bits_);
};

void HistoricalTicksRequest::clear_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.contract_ != nullptr) _impl_.contract_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
HistoricalTicksRequest::HistoricalTicksRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.HistoricalTicksRequest)
}
inline PROTOBUF_NDEBUG_INLINE HistoricalTicksRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protobuf::HistoricalTicksRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        miscoptions_{visibility, arena, from.miscoptions_},
        startdatetime_(arena, from.startdatetime_),
        enddatetime_(arena, from.enddatetime_),
        whattoshow_(arena, from.whattoshow_) {}

HistoricalTicksRequest::HistoricalTicksRequest(
    ::google::protobuf::Arena* arena,
    const HistoricalTicksRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  HistoricalTicksRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.contract_ = (cached_has_bits & 0x00000008u) ? ::google::protobuf::Message::CopyConstruct<::protobuf::Contract>(
                              arena, *from._impl_.contract_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, reqid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, reqid_),
           offsetof(Impl_, ignoresize_) -
               offsetof(Impl_, reqid_) +
               sizeof(Impl_::ignoresize_));

  // @@protoc_insertion_point(copy_constructor:protobuf.HistoricalTicksRequest)
}
inline PROTOBUF_NDEBUG_INLINE HistoricalTicksRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        miscoptions_{visibility, arena},
        startdatetime_(arena),
        enddatetime_(arena),
        whattoshow_(arena) {}

inline void HistoricalTicksRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, contract_),
           0,
           offsetof(Impl_, ignoresize_) -
               offsetof(Impl_, contract_) +
               sizeof(Impl_::ignoresize_));
}
HistoricalTicksRequest::~HistoricalTicksRequest() {
  // @@protoc_insertion_point(destructor:protobuf.HistoricalTicksRequest)
  SharedDtor(*this);
}
inline void HistoricalTicksRequest::SharedDtor(MessageLite& self) {
  HistoricalTicksRequest& this_ = static_cast<HistoricalTicksRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.startdatetime_.Destroy();
  this_._impl_.enddatetime_.Destroy();
  this_._impl_.whattoshow_.Destroy();
  delete this_._impl_.contract_;
  this_._impl_.~Impl_();
}

inline void* HistoricalTicksRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) HistoricalTicksRequest(arena);
}
constexpr auto HistoricalTicksRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.miscoptions_) +
          decltype(HistoricalTicksRequest::_impl_.miscoptions_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.miscoptions_) +
          decltype(HistoricalTicksRequest::_impl_.miscoptions_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(HistoricalTicksRequest), alignof(HistoricalTicksRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&HistoricalTicksRequest::PlacementNew_,
                                 sizeof(HistoricalTicksRequest),
                                 alignof(HistoricalTicksRequest));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull HistoricalTicksRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_HistoricalTicksRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &HistoricalTicksRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<HistoricalTicksRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &HistoricalTicksRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<HistoricalTicksRequest>(), &HistoricalTicksRequest::ByteSizeLong,
            &HistoricalTicksRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_._cached_size_),
        false,
    },
    &HistoricalTicksRequest::kDescriptorMethods,
    &descriptor_table_HistoricalTicksRequest_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* HistoricalTicksRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 9, 2, 93, 2> HistoricalTicksRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_._has_bits_),
    0, // no _extensions_
    9, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::HistoricalTicksRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional bool ignoreSize = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(HistoricalTicksRequest, _impl_.ignoresize_), 7>(),
     {64, 7, 0, PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.ignoresize_)}},
    // optional int32 reqId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(HistoricalTicksRequest, _impl_.reqid_), 4>(),
     {8, 4, 0, PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.reqid_)}},
    // optional .protobuf.Contract contract = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 3, 0, PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.contract_)}},
    // optional string startDateTime = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.startdatetime_)}},
    // optional string endDateTime = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0, PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.enddatetime_)}},
    // optional int32 numberOfTicks = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(HistoricalTicksRequest, _impl_.numberofticks_), 5>(),
     {40, 5, 0, PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.numberofticks_)}},
    // optional string whatToShow = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 2, 0, PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.whattoshow_)}},
    // optional bool useRTH = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(HistoricalTicksRequest, _impl_.userth_), 6>(),
     {56, 6, 0, PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.userth_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 reqId = 1;
    {PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.reqid_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional .protobuf.Contract contract = 2;
    {PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.contract_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional string startDateTime = 3;
    {PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.startdatetime_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string endDateTime = 4;
    {PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.enddatetime_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int32 numberOfTicks = 5;
    {PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.numberofticks_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string whatToShow = 6;
    {PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.whattoshow_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional bool useRTH = 7;
    {PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.userth_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool ignoreSize = 8;
    {PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.ignoresize_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // map<string, string> miscOptions = 9;
    {PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.miscoptions_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetTable<::protobuf::Contract>()},
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(HistoricalTicksRequest()._impl_.miscoptions_)>(
        1, 0, 0, 9,
        9)},
  }}, {{
    "\37\0\0\15\13\0\12\0\0\13\0\0\0\0\0\0"
    "protobuf.HistoricalTicksRequest"
    "startDateTime"
    "endDateTime"
    "whatToShow"
    "miscOptions"
  }},
};

PROTOBUF_NOINLINE void HistoricalTicksRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.HistoricalTicksRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.miscoptions_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.startdatetime_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.enddatetime_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.whattoshow_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.contract_ != nullptr);
      _impl_.contract_->Clear();
    }
  }
  if (cached_has_bits & 0x000000f0u) {
    ::memset(&_impl_.reqid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.ignoresize_) -
        reinterpret_cast<char*>(&_impl_.reqid_)) + sizeof(_impl_.ignoresize_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* HistoricalTicksRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const HistoricalTicksRequest& this_ = static_cast<const HistoricalTicksRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* HistoricalTicksRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const HistoricalTicksRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protobuf.HistoricalTicksRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 reqId = 1;
          if (cached_has_bits & 0x00000010u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_reqid(), target);
          }

          // optional .protobuf.Contract contract = 2;
          if (cached_has_bits & 0x00000008u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.contract_, this_._impl_.contract_->GetCachedSize(), target,
                stream);
          }

          // optional string startDateTime = 3;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_startdatetime();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.HistoricalTicksRequest.startDateTime");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // optional string endDateTime = 4;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_enddatetime();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.HistoricalTicksRequest.endDateTime");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // optional int32 numberOfTicks = 5;
          if (cached_has_bits & 0x00000020u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<5>(
                    stream, this_._internal_numberofticks(), target);
          }

          // optional string whatToShow = 6;
          if (cached_has_bits & 0x00000004u) {
            const std::string& _s = this_._internal_whattoshow();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.HistoricalTicksRequest.whatToShow");
            target = stream->WriteStringMaybeAliased(6, _s, target);
          }

          // optional bool useRTH = 7;
          if (cached_has_bits & 0x00000040u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                7, this_._internal_userth(), target);
          }

          // optional bool ignoreSize = 8;
          if (cached_has_bits & 0x00000080u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                8, this_._internal_ignoresize(), target);
          }

          // map<string, string> miscOptions = 9;
          if (!this_._internal_miscoptions().empty()) {
            using MapType = ::google::protobuf::Map<std::string, std::string>;
            using WireHelper = _pbi::MapEntryFuncs<std::string, std::string,
                                           _pbi::WireFormatLite::TYPE_STRING,
                                           _pbi::WireFormatLite::TYPE_STRING>;
            const auto& field = this_._internal_miscoptions();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    9, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.HistoricalTicksRequest.miscOptions");
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.HistoricalTicksRequest.miscOptions");
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    9, entry.first, entry.second, target, stream);
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.HistoricalTicksRequest.miscOptions");
                ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                    entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.HistoricalTicksRequest.miscOptions");
              }
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protobuf.HistoricalTicksRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t HistoricalTicksRequest::ByteSizeLong(const MessageLite& base) {
          const HistoricalTicksRequest& this_ = static_cast<const HistoricalTicksRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t HistoricalTicksRequest::ByteSizeLong() const {
          const HistoricalTicksRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protobuf.HistoricalTicksRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<string, string> miscOptions = 9;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_miscoptions_size());
              for (const auto& entry : this_._internal_miscoptions()) {
                total_size += _pbi::MapEntryFuncs<std::string, std::string,
                                               _pbi::WireFormatLite::TYPE_STRING,
                                               _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x000000ffu) {
            // optional string startDateTime = 3;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_startdatetime());
            }
            // optional string endDateTime = 4;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_enddatetime());
            }
            // optional string whatToShow = 6;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_whattoshow());
            }
            // optional .protobuf.Contract contract = 2;
            if (cached_has_bits & 0x00000008u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.contract_);
            }
            // optional int32 reqId = 1;
            if (cached_has_bits & 0x00000010u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_reqid());
            }
            // optional int32 numberOfTicks = 5;
            if (cached_has_bits & 0x00000020u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_numberofticks());
            }
            // optional bool useRTH = 7;
            if (cached_has_bits & 0x00000040u) {
              total_size += 2;
            }
            // optional bool ignoreSize = 8;
            if (cached_has_bits & 0x00000080u) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void HistoricalTicksRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<HistoricalTicksRequest*>(&to_msg);
  auto& from = static_cast<const HistoricalTicksRequest&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.HistoricalTicksRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.miscoptions_.MergeFrom(from._impl_.miscoptions_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_startdatetime(from._internal_startdatetime());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_enddatetime(from._internal_enddatetime());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_whattoshow(from._internal_whattoshow());
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(from._impl_.contract_ != nullptr);
      if (_this->_impl_.contract_ == nullptr) {
        _this->_impl_.contract_ =
            ::google::protobuf::Message::CopyConstruct<::protobuf::Contract>(arena, *from._impl_.contract_);
      } else {
        _this->_impl_.contract_->MergeFrom(*from._impl_.contract_);
      }
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.reqid_ = from._impl_.reqid_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.numberofticks_ = from._impl_.numberofticks_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.userth_ = from._impl_.userth_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.ignoresize_ = from._impl_.ignoresize_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void HistoricalTicksRequest::CopyFrom(const HistoricalTicksRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.HistoricalTicksRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HistoricalTicksRequest::InternalSwap(HistoricalTicksRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.miscoptions_.InternalSwap(&other->_impl_.miscoptions_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.startdatetime_, &other->_impl_.startdatetime_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.enddatetime_, &other->_impl_.enddatetime_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.whattoshow_, &other->_impl_.whattoshow_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.ignoresize_)
      + sizeof(HistoricalTicksRequest::_impl_.ignoresize_)
      - PROTOBUF_FIELD_OFFSET(HistoricalTicksRequest, _impl_.contract_)>(
          reinterpret_cast<char*>(&_impl_.contract_),
          reinterpret_cast<char*>(&other->_impl_.contract_));
}

::google::protobuf::Metadata HistoricalTicksRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_HistoricalTicksRequest_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
