// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ManagedAccounts.proto
// Protobuf C++ Version: 5.29.3

#include "ManagedAccounts.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {

inline constexpr ManagedAccounts::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        accountslist_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ManagedAccounts::ManagedAccounts(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ManagedAccountsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ManagedAccountsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ManagedAccountsDefaultTypeInternal() {}
  union {
    ManagedAccounts _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ManagedAccountsDefaultTypeInternal _ManagedAccounts_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ManagedAccounts_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ManagedAccounts_2eproto = nullptr;
const ::uint32_t
    TableStruct_ManagedAccounts_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protobuf::ManagedAccounts, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::ManagedAccounts, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::ManagedAccounts, _impl_.accountslist_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::protobuf::ManagedAccounts)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_ManagedAccounts_default_instance_._instance,
};
const char descriptor_table_protodef_ManagedAccounts_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025ManagedAccounts.proto\022\010protobuf\"=\n\017Man"
    "agedAccounts\022\031\n\014accountsList\030\001 \001(\tH\000\210\001\001B"
    "\017\n\r_accountsListB\?\n\026com.ib.client.protob"
    "ufB\024ManagedAccountsProto\252\002\016IBApi.protobu"
    "fb\006proto3"
};
static ::absl::once_flag descriptor_table_ManagedAccounts_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ManagedAccounts_2eproto = {
    false,
    false,
    169,
    descriptor_table_protodef_ManagedAccounts_2eproto,
    "ManagedAccounts.proto",
    &descriptor_table_ManagedAccounts_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_ManagedAccounts_2eproto::offsets,
    file_level_enum_descriptors_ManagedAccounts_2eproto,
    file_level_service_descriptors_ManagedAccounts_2eproto,
};
namespace protobuf {
// ===================================================================

class ManagedAccounts::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ManagedAccounts>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ManagedAccounts, _impl_._has_bits_);
};

ManagedAccounts::ManagedAccounts(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.ManagedAccounts)
}
inline PROTOBUF_NDEBUG_INLINE ManagedAccounts::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protobuf::ManagedAccounts& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        accountslist_(arena, from.accountslist_) {}

ManagedAccounts::ManagedAccounts(
    ::google::protobuf::Arena* arena,
    const ManagedAccounts& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ManagedAccounts* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:protobuf.ManagedAccounts)
}
inline PROTOBUF_NDEBUG_INLINE ManagedAccounts::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        accountslist_(arena) {}

inline void ManagedAccounts::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ManagedAccounts::~ManagedAccounts() {
  // @@protoc_insertion_point(destructor:protobuf.ManagedAccounts)
  SharedDtor(*this);
}
inline void ManagedAccounts::SharedDtor(MessageLite& self) {
  ManagedAccounts& this_ = static_cast<ManagedAccounts&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.accountslist_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ManagedAccounts::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ManagedAccounts(arena);
}
constexpr auto ManagedAccounts::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ManagedAccounts),
                                            alignof(ManagedAccounts));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ManagedAccounts::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ManagedAccounts_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ManagedAccounts::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ManagedAccounts>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ManagedAccounts::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ManagedAccounts>(), &ManagedAccounts::ByteSizeLong,
            &ManagedAccounts::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ManagedAccounts, _impl_._cached_size_),
        false,
    },
    &ManagedAccounts::kDescriptorMethods,
    &descriptor_table_ManagedAccounts_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ManagedAccounts::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 45, 2> ManagedAccounts::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ManagedAccounts, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::ManagedAccounts>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string accountsList = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ManagedAccounts, _impl_.accountslist_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string accountsList = 1;
    {PROTOBUF_FIELD_OFFSET(ManagedAccounts, _impl_.accountslist_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\14\0\0\0\0\0\0"
    "protobuf.ManagedAccounts"
    "accountsList"
  }},
};

PROTOBUF_NOINLINE void ManagedAccounts::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.ManagedAccounts)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.accountslist_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ManagedAccounts::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ManagedAccounts& this_ = static_cast<const ManagedAccounts&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ManagedAccounts::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ManagedAccounts& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protobuf.ManagedAccounts)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string accountsList = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_accountslist();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.ManagedAccounts.accountsList");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protobuf.ManagedAccounts)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ManagedAccounts::ByteSizeLong(const MessageLite& base) {
          const ManagedAccounts& this_ = static_cast<const ManagedAccounts&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ManagedAccounts::ByteSizeLong() const {
          const ManagedAccounts& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protobuf.ManagedAccounts)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // optional string accountsList = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_accountslist());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ManagedAccounts::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ManagedAccounts*>(&to_msg);
  auto& from = static_cast<const ManagedAccounts&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.ManagedAccounts)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_internal_set_accountslist(from._internal_accountslist());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ManagedAccounts::CopyFrom(const ManagedAccounts& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.ManagedAccounts)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ManagedAccounts::InternalSwap(ManagedAccounts* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.accountslist_, &other->_impl_.accountslist_, arena);
}

::google::protobuf::Metadata ManagedAccounts::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ManagedAccounts_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
