// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MarketDepthData.proto
// Protobuf C++ Version: 5.29.3

#ifndef MarketDepthData_2eproto_2epb_2eh
#define MarketDepthData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_MarketDepthData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_MarketDepthData_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_MarketDepthData_2eproto;
namespace protobuf {
class MarketDepthData;
struct MarketDepthDataDefaultTypeInternal;
extern MarketDepthDataDefaultTypeInternal _MarketDepthData_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class MarketDepthData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.MarketDepthData) */ {
 public:
  inline MarketDepthData() : MarketDepthData(nullptr) {}
  ~MarketDepthData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MarketDepthData* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MarketDepthData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MarketDepthData(
      ::google::protobuf::internal::ConstantInitialized);

  inline MarketDepthData(const MarketDepthData& from) : MarketDepthData(nullptr, from) {}
  inline MarketDepthData(MarketDepthData&& from) noexcept
      : MarketDepthData(nullptr, std::move(from)) {}
  inline MarketDepthData& operator=(const MarketDepthData& from) {
    CopyFrom(from);
    return *this;
  }
  inline MarketDepthData& operator=(MarketDepthData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MarketDepthData& default_instance() {
    return *internal_default_instance();
  }
  static inline const MarketDepthData* internal_default_instance() {
    return reinterpret_cast<const MarketDepthData*>(
        &_MarketDepthData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MarketDepthData& a, MarketDepthData& b) { a.Swap(&b); }
  inline void Swap(MarketDepthData* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MarketDepthData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MarketDepthData* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MarketDepthData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MarketDepthData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MarketDepthData& from) { MarketDepthData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MarketDepthData* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.MarketDepthData"; }

 protected:
  explicit MarketDepthData(::google::protobuf::Arena* arena);
  MarketDepthData(::google::protobuf::Arena* arena, const MarketDepthData& from);
  MarketDepthData(::google::protobuf::Arena* arena, MarketDepthData&& from) noexcept
      : MarketDepthData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSizeFieldNumber = 5,
    kMarketMakerFieldNumber = 6,
    kPositionFieldNumber = 1,
    kOperationFieldNumber = 2,
    kPriceFieldNumber = 4,
    kSideFieldNumber = 3,
    kIsSmartDepthFieldNumber = 7,
  };
  // optional string size = 5;
  bool has_size() const;
  void clear_size() ;
  const std::string& size() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_size(Arg_&& arg, Args_... args);
  std::string* mutable_size();
  PROTOBUF_NODISCARD std::string* release_size();
  void set_allocated_size(std::string* value);

  private:
  const std::string& _internal_size() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_size(
      const std::string& value);
  std::string* _internal_mutable_size();

  public:
  // optional string marketMaker = 6;
  bool has_marketmaker() const;
  void clear_marketmaker() ;
  const std::string& marketmaker() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_marketmaker(Arg_&& arg, Args_... args);
  std::string* mutable_marketmaker();
  PROTOBUF_NODISCARD std::string* release_marketmaker();
  void set_allocated_marketmaker(std::string* value);

  private:
  const std::string& _internal_marketmaker() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_marketmaker(
      const std::string& value);
  std::string* _internal_mutable_marketmaker();

  public:
  // optional int32 position = 1;
  bool has_position() const;
  void clear_position() ;
  ::int32_t position() const;
  void set_position(::int32_t value);

  private:
  ::int32_t _internal_position() const;
  void _internal_set_position(::int32_t value);

  public:
  // optional int32 operation = 2;
  bool has_operation() const;
  void clear_operation() ;
  ::int32_t operation() const;
  void set_operation(::int32_t value);

  private:
  ::int32_t _internal_operation() const;
  void _internal_set_operation(::int32_t value);

  public:
  // optional double price = 4;
  bool has_price() const;
  void clear_price() ;
  double price() const;
  void set_price(double value);

  private:
  double _internal_price() const;
  void _internal_set_price(double value);

  public:
  // optional int32 side = 3;
  bool has_side() const;
  void clear_side() ;
  ::int32_t side() const;
  void set_side(::int32_t value);

  private:
  ::int32_t _internal_side() const;
  void _internal_set_side(::int32_t value);

  public:
  // optional bool isSmartDepth = 7;
  bool has_issmartdepth() const;
  void clear_issmartdepth() ;
  bool issmartdepth() const;
  void set_issmartdepth(bool value);

  private:
  bool _internal_issmartdepth() const;
  void _internal_set_issmartdepth(bool value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.MarketDepthData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 0,
      48, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MarketDepthData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr size_;
    ::google::protobuf::internal::ArenaStringPtr marketmaker_;
    ::int32_t position_;
    ::int32_t operation_;
    double price_;
    ::int32_t side_;
    bool issmartdepth_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MarketDepthData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MarketDepthData

// optional int32 position = 1;
inline bool MarketDepthData::has_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void MarketDepthData::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t MarketDepthData::position() const {
  // @@protoc_insertion_point(field_get:protobuf.MarketDepthData.position)
  return _internal_position();
}
inline void MarketDepthData::set_position(::int32_t value) {
  _internal_set_position(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:protobuf.MarketDepthData.position)
}
inline ::int32_t MarketDepthData::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.position_;
}
inline void MarketDepthData::_internal_set_position(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.position_ = value;
}

// optional int32 operation = 2;
inline bool MarketDepthData::has_operation() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void MarketDepthData::clear_operation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.operation_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t MarketDepthData::operation() const {
  // @@protoc_insertion_point(field_get:protobuf.MarketDepthData.operation)
  return _internal_operation();
}
inline void MarketDepthData::set_operation(::int32_t value) {
  _internal_set_operation(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:protobuf.MarketDepthData.operation)
}
inline ::int32_t MarketDepthData::_internal_operation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.operation_;
}
inline void MarketDepthData::_internal_set_operation(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.operation_ = value;
}

// optional int32 side = 3;
inline bool MarketDepthData::has_side() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void MarketDepthData::clear_side() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.side_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t MarketDepthData::side() const {
  // @@protoc_insertion_point(field_get:protobuf.MarketDepthData.side)
  return _internal_side();
}
inline void MarketDepthData::set_side(::int32_t value) {
  _internal_set_side(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:protobuf.MarketDepthData.side)
}
inline ::int32_t MarketDepthData::_internal_side() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.side_;
}
inline void MarketDepthData::_internal_set_side(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.side_ = value;
}

// optional double price = 4;
inline bool MarketDepthData::has_price() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void MarketDepthData::clear_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline double MarketDepthData::price() const {
  // @@protoc_insertion_point(field_get:protobuf.MarketDepthData.price)
  return _internal_price();
}
inline void MarketDepthData::set_price(double value) {
  _internal_set_price(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:protobuf.MarketDepthData.price)
}
inline double MarketDepthData::_internal_price() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.price_;
}
inline void MarketDepthData::_internal_set_price(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_ = value;
}

// optional string size = 5;
inline bool MarketDepthData::has_size() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void MarketDepthData::clear_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MarketDepthData::size() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.MarketDepthData.size)
  return _internal_size();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MarketDepthData::set_size(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.size_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.MarketDepthData.size)
}
inline std::string* MarketDepthData::mutable_size() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_size();
  // @@protoc_insertion_point(field_mutable:protobuf.MarketDepthData.size)
  return _s;
}
inline const std::string& MarketDepthData::_internal_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.size_.Get();
}
inline void MarketDepthData::_internal_set_size(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.size_.Set(value, GetArena());
}
inline std::string* MarketDepthData::_internal_mutable_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.size_.Mutable( GetArena());
}
inline std::string* MarketDepthData::release_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.MarketDepthData.size)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.size_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.size_.Set("", GetArena());
  }
  return released;
}
inline void MarketDepthData::set_allocated_size(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.size_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.size_.IsDefault()) {
    _impl_.size_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.MarketDepthData.size)
}

// optional string marketMaker = 6;
inline bool MarketDepthData::has_marketmaker() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void MarketDepthData::clear_marketmaker() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.marketmaker_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& MarketDepthData::marketmaker() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.MarketDepthData.marketMaker)
  return _internal_marketmaker();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void MarketDepthData::set_marketmaker(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.marketmaker_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.MarketDepthData.marketMaker)
}
inline std::string* MarketDepthData::mutable_marketmaker() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_marketmaker();
  // @@protoc_insertion_point(field_mutable:protobuf.MarketDepthData.marketMaker)
  return _s;
}
inline const std::string& MarketDepthData::_internal_marketmaker() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.marketmaker_.Get();
}
inline void MarketDepthData::_internal_set_marketmaker(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.marketmaker_.Set(value, GetArena());
}
inline std::string* MarketDepthData::_internal_mutable_marketmaker() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.marketmaker_.Mutable( GetArena());
}
inline std::string* MarketDepthData::release_marketmaker() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.MarketDepthData.marketMaker)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.marketmaker_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.marketmaker_.Set("", GetArena());
  }
  return released;
}
inline void MarketDepthData::set_allocated_marketmaker(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.marketmaker_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.marketmaker_.IsDefault()) {
    _impl_.marketmaker_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.MarketDepthData.marketMaker)
}

// optional bool isSmartDepth = 7;
inline bool MarketDepthData::has_issmartdepth() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void MarketDepthData::clear_issmartdepth() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.issmartdepth_ = false;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline bool MarketDepthData::issmartdepth() const {
  // @@protoc_insertion_point(field_get:protobuf.MarketDepthData.isSmartDepth)
  return _internal_issmartdepth();
}
inline void MarketDepthData::set_issmartdepth(bool value) {
  _internal_set_issmartdepth(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:protobuf.MarketDepthData.isSmartDepth)
}
inline bool MarketDepthData::_internal_issmartdepth() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.issmartdepth_;
}
inline void MarketDepthData::_internal_set_issmartdepth(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.issmartdepth_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // MarketDepthData_2eproto_2epb_2eh
