// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PortfolioValue.proto
// Protobuf C++ Version: 5.29.3

#include "PortfolioValue.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {

inline constexpr PortfolioValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        position_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        accountname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        contract_{nullptr},
        marketprice_{0},
        marketvalue_{0},
        averagecost_{0},
        unrealizedpnl_{0},
        realizedpnl_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PortfolioValue::PortfolioValue(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PortfolioValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PortfolioValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PortfolioValueDefaultTypeInternal() {}
  union {
    PortfolioValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PortfolioValueDefaultTypeInternal _PortfolioValue_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_PortfolioValue_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_PortfolioValue_2eproto = nullptr;
const ::uint32_t
    TableStruct_PortfolioValue_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, _impl_.contract_),
        PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, _impl_.position_),
        PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, _impl_.marketprice_),
        PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, _impl_.marketvalue_),
        PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, _impl_.averagecost_),
        PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, _impl_.unrealizedpnl_),
        PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, _impl_.realizedpnl_),
        PROTOBUF_FIELD_OFFSET(::protobuf::PortfolioValue, _impl_.accountname_),
        2,
        0,
        3,
        4,
        5,
        6,
        7,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 16, -1, sizeof(::protobuf::PortfolioValue)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_PortfolioValue_default_instance_._instance,
};
const char descriptor_table_protodef_PortfolioValue_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024PortfolioValue.proto\022\010protobuf\032\016Contra"
    "ct.proto\"\354\002\n\016PortfolioValue\022)\n\010contract\030"
    "\001 \001(\0132\022.protobuf.ContractH\000\210\001\001\022\025\n\010positi"
    "on\030\002 \001(\tH\001\210\001\001\022\030\n\013marketPrice\030\003 \001(\001H\002\210\001\001\022"
    "\030\n\013marketValue\030\004 \001(\001H\003\210\001\001\022\030\n\013averageCost"
    "\030\005 \001(\001H\004\210\001\001\022\032\n\runrealizedPNL\030\006 \001(\001H\005\210\001\001\022"
    "\030\n\013realizedPNL\030\007 \001(\001H\006\210\001\001\022\030\n\013accountName"
    "\030\010 \001(\tH\007\210\001\001B\013\n\t_contractB\013\n\t_positionB\016\n"
    "\014_marketPriceB\016\n\014_marketValueB\016\n\014_averag"
    "eCostB\020\n\016_unrealizedPNLB\016\n\014_realizedPNLB"
    "\016\n\014_accountNameB>\n\026com.ib.client.protobu"
    "fB\023PortfolioValueProto\252\002\016IBApi.protobufb"
    "\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_PortfolioValue_2eproto_deps[1] =
    {
        &::descriptor_table_Contract_2eproto,
};
static ::absl::once_flag descriptor_table_PortfolioValue_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_PortfolioValue_2eproto = {
    false,
    false,
    487,
    descriptor_table_protodef_PortfolioValue_2eproto,
    "PortfolioValue.proto",
    &descriptor_table_PortfolioValue_2eproto_once,
    descriptor_table_PortfolioValue_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_PortfolioValue_2eproto::offsets,
    file_level_enum_descriptors_PortfolioValue_2eproto,
    file_level_service_descriptors_PortfolioValue_2eproto,
};
namespace protobuf {
// ===================================================================

class PortfolioValue::_Internal {
 public:
  using HasBits =
      decltype(std::declval<PortfolioValue>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_._has_bits_);
};

void PortfolioValue::clear_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.contract_ != nullptr) _impl_.contract_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
PortfolioValue::PortfolioValue(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.PortfolioValue)
}
inline PROTOBUF_NDEBUG_INLINE PortfolioValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protobuf::PortfolioValue& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        position_(arena, from.position_),
        accountname_(arena, from.accountname_) {}

PortfolioValue::PortfolioValue(
    ::google::protobuf::Arena* arena,
    const PortfolioValue& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PortfolioValue* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.contract_ = (cached_has_bits & 0x00000004u) ? ::google::protobuf::Message::CopyConstruct<::protobuf::Contract>(
                              arena, *from._impl_.contract_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, marketprice_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, marketprice_),
           offsetof(Impl_, realizedpnl_) -
               offsetof(Impl_, marketprice_) +
               sizeof(Impl_::realizedpnl_));

  // @@protoc_insertion_point(copy_constructor:protobuf.PortfolioValue)
}
inline PROTOBUF_NDEBUG_INLINE PortfolioValue::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        position_(arena),
        accountname_(arena) {}

inline void PortfolioValue::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, contract_),
           0,
           offsetof(Impl_, realizedpnl_) -
               offsetof(Impl_, contract_) +
               sizeof(Impl_::realizedpnl_));
}
PortfolioValue::~PortfolioValue() {
  // @@protoc_insertion_point(destructor:protobuf.PortfolioValue)
  SharedDtor(*this);
}
inline void PortfolioValue::SharedDtor(MessageLite& self) {
  PortfolioValue& this_ = static_cast<PortfolioValue&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.position_.Destroy();
  this_._impl_.accountname_.Destroy();
  delete this_._impl_.contract_;
  this_._impl_.~Impl_();
}

inline void* PortfolioValue::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PortfolioValue(arena);
}
constexpr auto PortfolioValue::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PortfolioValue),
                                            alignof(PortfolioValue));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PortfolioValue::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PortfolioValue_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PortfolioValue::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PortfolioValue>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PortfolioValue::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PortfolioValue>(), &PortfolioValue::ByteSizeLong,
            &PortfolioValue::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_._cached_size_),
        false,
    },
    &PortfolioValue::kDescriptorMethods,
    &descriptor_table_PortfolioValue_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PortfolioValue::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 1, 59, 2> PortfolioValue::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::PortfolioValue>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string accountName = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 1, 0, PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.accountname_)}},
    // optional .protobuf.Contract contract = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 2, 0, PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.contract_)}},
    // optional string position = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.position_)}},
    // optional double marketPrice = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 3, 0, PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.marketprice_)}},
    // optional double marketValue = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 4, 0, PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.marketvalue_)}},
    // optional double averageCost = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 5, 0, PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.averagecost_)}},
    // optional double unrealizedPNL = 6;
    {::_pbi::TcParser::FastF64S1,
     {49, 6, 0, PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.unrealizedpnl_)}},
    // optional double realizedPNL = 7;
    {::_pbi::TcParser::FastF64S1,
     {57, 7, 0, PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.realizedpnl_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .protobuf.Contract contract = 1;
    {PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.contract_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional string position = 2;
    {PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.position_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional double marketPrice = 3;
    {PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.marketprice_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // optional double marketValue = 4;
    {PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.marketvalue_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // optional double averageCost = 5;
    {PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.averagecost_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // optional double unrealizedPNL = 6;
    {PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.unrealizedpnl_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // optional double realizedPNL = 7;
    {PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.realizedpnl_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // optional string accountName = 8;
    {PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.accountname_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::protobuf::Contract>()},
  }}, {{
    "\27\0\10\0\0\0\0\0\13\0\0\0\0\0\0\0"
    "protobuf.PortfolioValue"
    "position"
    "accountName"
  }},
};

PROTOBUF_NOINLINE void PortfolioValue::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.PortfolioValue)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.position_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.accountname_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.contract_ != nullptr);
      _impl_.contract_->Clear();
    }
  }
  if (cached_has_bits & 0x000000f8u) {
    ::memset(&_impl_.marketprice_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.realizedpnl_) -
        reinterpret_cast<char*>(&_impl_.marketprice_)) + sizeof(_impl_.realizedpnl_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PortfolioValue::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PortfolioValue& this_ = static_cast<const PortfolioValue&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PortfolioValue::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PortfolioValue& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protobuf.PortfolioValue)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional .protobuf.Contract contract = 1;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.contract_, this_._impl_.contract_->GetCachedSize(), target,
                stream);
          }

          // optional string position = 2;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_position();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.PortfolioValue.position");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // optional double marketPrice = 3;
          if (cached_has_bits & 0x00000008u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_marketprice(), target);
          }

          // optional double marketValue = 4;
          if (cached_has_bits & 0x00000010u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                4, this_._internal_marketvalue(), target);
          }

          // optional double averageCost = 5;
          if (cached_has_bits & 0x00000020u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                5, this_._internal_averagecost(), target);
          }

          // optional double unrealizedPNL = 6;
          if (cached_has_bits & 0x00000040u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                6, this_._internal_unrealizedpnl(), target);
          }

          // optional double realizedPNL = 7;
          if (cached_has_bits & 0x00000080u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                7, this_._internal_realizedpnl(), target);
          }

          // optional string accountName = 8;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_accountname();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobuf.PortfolioValue.accountName");
            target = stream->WriteStringMaybeAliased(8, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protobuf.PortfolioValue)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PortfolioValue::ByteSizeLong(const MessageLite& base) {
          const PortfolioValue& this_ = static_cast<const PortfolioValue&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PortfolioValue::ByteSizeLong() const {
          const PortfolioValue& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protobuf.PortfolioValue)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x000000ffu) {
            // optional string position = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_position());
            }
            // optional string accountName = 8;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_accountname());
            }
            // optional .protobuf.Contract contract = 1;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.contract_);
            }
            // optional double marketPrice = 3;
            if (cached_has_bits & 0x00000008u) {
              total_size += 9;
            }
            // optional double marketValue = 4;
            if (cached_has_bits & 0x00000010u) {
              total_size += 9;
            }
            // optional double averageCost = 5;
            if (cached_has_bits & 0x00000020u) {
              total_size += 9;
            }
            // optional double unrealizedPNL = 6;
            if (cached_has_bits & 0x00000040u) {
              total_size += 9;
            }
            // optional double realizedPNL = 7;
            if (cached_has_bits & 0x00000080u) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PortfolioValue::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PortfolioValue*>(&to_msg);
  auto& from = static_cast<const PortfolioValue&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.PortfolioValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_position(from._internal_position());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_accountname(from._internal_accountname());
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(from._impl_.contract_ != nullptr);
      if (_this->_impl_.contract_ == nullptr) {
        _this->_impl_.contract_ =
            ::google::protobuf::Message::CopyConstruct<::protobuf::Contract>(arena, *from._impl_.contract_);
      } else {
        _this->_impl_.contract_->MergeFrom(*from._impl_.contract_);
      }
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.marketprice_ = from._impl_.marketprice_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.marketvalue_ = from._impl_.marketvalue_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.averagecost_ = from._impl_.averagecost_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.unrealizedpnl_ = from._impl_.unrealizedpnl_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.realizedpnl_ = from._impl_.realizedpnl_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PortfolioValue::CopyFrom(const PortfolioValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.PortfolioValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PortfolioValue::InternalSwap(PortfolioValue* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.position_, &other->_impl_.position_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.accountname_, &other->_impl_.accountname_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.realizedpnl_)
      + sizeof(PortfolioValue::_impl_.realizedpnl_)
      - PROTOBUF_FIELD_OFFSET(PortfolioValue, _impl_.contract_)>(
          reinterpret_cast<char*>(&_impl_.contract_),
          reinterpret_cast<char*>(&other->_impl_.contract_));
}

::google::protobuf::Metadata PortfolioValue::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_PortfolioValue_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
