// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RealTimeBarsRequest.proto
// Protobuf C++ Version: 5.29.3

#ifndef RealTimeBarsRequest_2eproto_2epb_2eh
#define RealTimeBarsRequest_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
#include "Contract.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_RealTimeBarsRequest_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_RealTimeBarsRequest_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_RealTimeBarsRequest_2eproto;
namespace protobuf {
class RealTimeBarsRequest;
struct RealTimeBarsRequestDefaultTypeInternal;
extern RealTimeBarsRequestDefaultTypeInternal _RealTimeBarsRequest_default_instance_;
class RealTimeBarsRequest_RealTimeBarsOptionsEntry_DoNotUse;
struct RealTimeBarsRequest_RealTimeBarsOptionsEntry_DoNotUseDefaultTypeInternal;
extern RealTimeBarsRequest_RealTimeBarsOptionsEntry_DoNotUseDefaultTypeInternal _RealTimeBarsRequest_RealTimeBarsOptionsEntry_DoNotUse_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class RealTimeBarsRequest_RealTimeBarsOptionsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  RealTimeBarsRequest_RealTimeBarsOptionsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RealTimeBarsRequest_RealTimeBarsOptionsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit RealTimeBarsRequest_RealTimeBarsOptionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const RealTimeBarsRequest_RealTimeBarsOptionsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const RealTimeBarsRequest_RealTimeBarsOptionsEntry_DoNotUse*>(
        &_RealTimeBarsRequest_RealTimeBarsOptionsEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_RealTimeBarsRequest_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      70, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class RealTimeBarsRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:protobuf.RealTimeBarsRequest) */ {
 public:
  inline RealTimeBarsRequest() : RealTimeBarsRequest(nullptr) {}
  ~RealTimeBarsRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RealTimeBarsRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RealTimeBarsRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RealTimeBarsRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline RealTimeBarsRequest(const RealTimeBarsRequest& from) : RealTimeBarsRequest(nullptr, from) {}
  inline RealTimeBarsRequest(RealTimeBarsRequest&& from) noexcept
      : RealTimeBarsRequest(nullptr, std::move(from)) {}
  inline RealTimeBarsRequest& operator=(const RealTimeBarsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RealTimeBarsRequest& operator=(RealTimeBarsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RealTimeBarsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const RealTimeBarsRequest* internal_default_instance() {
    return reinterpret_cast<const RealTimeBarsRequest*>(
        &_RealTimeBarsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RealTimeBarsRequest& a, RealTimeBarsRequest& b) { a.Swap(&b); }
  inline void Swap(RealTimeBarsRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RealTimeBarsRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RealTimeBarsRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RealTimeBarsRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RealTimeBarsRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RealTimeBarsRequest& from) { RealTimeBarsRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RealTimeBarsRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "protobuf.RealTimeBarsRequest"; }

 protected:
  explicit RealTimeBarsRequest(::google::protobuf::Arena* arena);
  RealTimeBarsRequest(::google::protobuf::Arena* arena, const RealTimeBarsRequest& from);
  RealTimeBarsRequest(::google::protobuf::Arena* arena, RealTimeBarsRequest&& from) noexcept
      : RealTimeBarsRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRealTimeBarsOptionsFieldNumber = 6,
    kWhatToShowFieldNumber = 4,
    kContractFieldNumber = 2,
    kReqIdFieldNumber = 1,
    kBarSizeFieldNumber = 3,
    kUseRTHFieldNumber = 5,
  };
  // map<string, string> realTimeBarsOptions = 6;
  int realtimebarsoptions_size() const;
  private:
  int _internal_realtimebarsoptions_size() const;

  public:
  void clear_realtimebarsoptions() ;
  const ::google::protobuf::Map<std::string, std::string>& realtimebarsoptions() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_realtimebarsoptions();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_realtimebarsoptions() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_realtimebarsoptions();

  public:
  // optional string whatToShow = 4;
  bool has_whattoshow() const;
  void clear_whattoshow() ;
  const std::string& whattoshow() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_whattoshow(Arg_&& arg, Args_... args);
  std::string* mutable_whattoshow();
  PROTOBUF_NODISCARD std::string* release_whattoshow();
  void set_allocated_whattoshow(std::string* value);

  private:
  const std::string& _internal_whattoshow() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_whattoshow(
      const std::string& value);
  std::string* _internal_mutable_whattoshow();

  public:
  // optional .protobuf.Contract contract = 2;
  bool has_contract() const;
  void clear_contract() ;
  const ::protobuf::Contract& contract() const;
  PROTOBUF_NODISCARD ::protobuf::Contract* release_contract();
  ::protobuf::Contract* mutable_contract();
  void set_allocated_contract(::protobuf::Contract* value);
  void unsafe_arena_set_allocated_contract(::protobuf::Contract* value);
  ::protobuf::Contract* unsafe_arena_release_contract();

  private:
  const ::protobuf::Contract& _internal_contract() const;
  ::protobuf::Contract* _internal_mutable_contract();

  public:
  // optional int32 reqId = 1;
  bool has_reqid() const;
  void clear_reqid() ;
  ::int32_t reqid() const;
  void set_reqid(::int32_t value);

  private:
  ::int32_t _internal_reqid() const;
  void _internal_set_reqid(::int32_t value);

  public:
  // optional int32 barSize = 3;
  bool has_barsize() const;
  void clear_barsize() ;
  ::int32_t barsize() const;
  void set_barsize(::int32_t value);

  private:
  ::int32_t _internal_barsize() const;
  void _internal_set_barsize(::int32_t value);

  public:
  // optional bool useRTH = 5;
  bool has_userth() const;
  void clear_userth() ;
  bool userth() const;
  void set_userth(bool value);

  private:
  bool _internal_userth() const;
  void _internal_set_userth(bool value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.RealTimeBarsRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 2,
      66, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RealTimeBarsRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapField<RealTimeBarsRequest_RealTimeBarsOptionsEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        realtimebarsoptions_;
    ::google::protobuf::internal::ArenaStringPtr whattoshow_;
    ::protobuf::Contract* contract_;
    ::int32_t reqid_;
    ::int32_t barsize_;
    bool userth_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RealTimeBarsRequest_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// RealTimeBarsRequest

// optional int32 reqId = 1;
inline bool RealTimeBarsRequest::has_reqid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void RealTimeBarsRequest::clear_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t RealTimeBarsRequest::reqid() const {
  // @@protoc_insertion_point(field_get:protobuf.RealTimeBarsRequest.reqId)
  return _internal_reqid();
}
inline void RealTimeBarsRequest::set_reqid(::int32_t value) {
  _internal_set_reqid(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:protobuf.RealTimeBarsRequest.reqId)
}
inline ::int32_t RealTimeBarsRequest::_internal_reqid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reqid_;
}
inline void RealTimeBarsRequest::_internal_set_reqid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_ = value;
}

// optional .protobuf.Contract contract = 2;
inline bool RealTimeBarsRequest::has_contract() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.contract_ != nullptr);
  return value;
}
inline const ::protobuf::Contract& RealTimeBarsRequest::_internal_contract() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::protobuf::Contract* p = _impl_.contract_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::Contract&>(::protobuf::_Contract_default_instance_);
}
inline const ::protobuf::Contract& RealTimeBarsRequest::contract() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.RealTimeBarsRequest.contract)
  return _internal_contract();
}
inline void RealTimeBarsRequest::unsafe_arena_set_allocated_contract(::protobuf::Contract* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.contract_);
  }
  _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.RealTimeBarsRequest.contract)
}
inline ::protobuf::Contract* RealTimeBarsRequest::release_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::protobuf::Contract* released = _impl_.contract_;
  _impl_.contract_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::protobuf::Contract* RealTimeBarsRequest::unsafe_arena_release_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.RealTimeBarsRequest.contract)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::protobuf::Contract* temp = _impl_.contract_;
  _impl_.contract_ = nullptr;
  return temp;
}
inline ::protobuf::Contract* RealTimeBarsRequest::_internal_mutable_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.contract_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::protobuf::Contract>(GetArena());
    _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(p);
  }
  return _impl_.contract_;
}
inline ::protobuf::Contract* RealTimeBarsRequest::mutable_contract() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::protobuf::Contract* _msg = _internal_mutable_contract();
  // @@protoc_insertion_point(field_mutable:protobuf.RealTimeBarsRequest.contract)
  return _msg;
}
inline void RealTimeBarsRequest::set_allocated_contract(::protobuf::Contract* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.contract_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.contract_ = reinterpret_cast<::protobuf::Contract*>(value);
  // @@protoc_insertion_point(field_set_allocated:protobuf.RealTimeBarsRequest.contract)
}

// optional int32 barSize = 3;
inline bool RealTimeBarsRequest::has_barsize() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void RealTimeBarsRequest::clear_barsize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.barsize_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t RealTimeBarsRequest::barsize() const {
  // @@protoc_insertion_point(field_get:protobuf.RealTimeBarsRequest.barSize)
  return _internal_barsize();
}
inline void RealTimeBarsRequest::set_barsize(::int32_t value) {
  _internal_set_barsize(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:protobuf.RealTimeBarsRequest.barSize)
}
inline ::int32_t RealTimeBarsRequest::_internal_barsize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.barsize_;
}
inline void RealTimeBarsRequest::_internal_set_barsize(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.barsize_ = value;
}

// optional string whatToShow = 4;
inline bool RealTimeBarsRequest::has_whattoshow() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void RealTimeBarsRequest::clear_whattoshow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.whattoshow_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RealTimeBarsRequest::whattoshow() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:protobuf.RealTimeBarsRequest.whatToShow)
  return _internal_whattoshow();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RealTimeBarsRequest::set_whattoshow(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.whattoshow_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:protobuf.RealTimeBarsRequest.whatToShow)
}
inline std::string* RealTimeBarsRequest::mutable_whattoshow() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_whattoshow();
  // @@protoc_insertion_point(field_mutable:protobuf.RealTimeBarsRequest.whatToShow)
  return _s;
}
inline const std::string& RealTimeBarsRequest::_internal_whattoshow() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.whattoshow_.Get();
}
inline void RealTimeBarsRequest::_internal_set_whattoshow(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.whattoshow_.Set(value, GetArena());
}
inline std::string* RealTimeBarsRequest::_internal_mutable_whattoshow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.whattoshow_.Mutable( GetArena());
}
inline std::string* RealTimeBarsRequest::release_whattoshow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:protobuf.RealTimeBarsRequest.whatToShow)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.whattoshow_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.whattoshow_.Set("", GetArena());
  }
  return released;
}
inline void RealTimeBarsRequest::set_allocated_whattoshow(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.whattoshow_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.whattoshow_.IsDefault()) {
    _impl_.whattoshow_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf.RealTimeBarsRequest.whatToShow)
}

// optional bool useRTH = 5;
inline bool RealTimeBarsRequest::has_userth() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void RealTimeBarsRequest::clear_userth() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userth_ = false;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline bool RealTimeBarsRequest::userth() const {
  // @@protoc_insertion_point(field_get:protobuf.RealTimeBarsRequest.useRTH)
  return _internal_userth();
}
inline void RealTimeBarsRequest::set_userth(bool value) {
  _internal_set_userth(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:protobuf.RealTimeBarsRequest.useRTH)
}
inline bool RealTimeBarsRequest::_internal_userth() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.userth_;
}
inline void RealTimeBarsRequest::_internal_set_userth(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userth_ = value;
}

// map<string, string> realTimeBarsOptions = 6;
inline int RealTimeBarsRequest::_internal_realtimebarsoptions_size() const {
  return _internal_realtimebarsoptions().size();
}
inline int RealTimeBarsRequest::realtimebarsoptions_size() const {
  return _internal_realtimebarsoptions_size();
}
inline void RealTimeBarsRequest::clear_realtimebarsoptions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.realtimebarsoptions_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& RealTimeBarsRequest::_internal_realtimebarsoptions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.realtimebarsoptions_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& RealTimeBarsRequest::realtimebarsoptions() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:protobuf.RealTimeBarsRequest.realTimeBarsOptions)
  return _internal_realtimebarsoptions();
}
inline ::google::protobuf::Map<std::string, std::string>* RealTimeBarsRequest::_internal_mutable_realtimebarsoptions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.realtimebarsoptions_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* RealTimeBarsRequest::mutable_realtimebarsoptions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:protobuf.RealTimeBarsRequest.realTimeBarsOptions)
  return _internal_mutable_realtimebarsoptions();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // RealTimeBarsRequest_2eproto_2epb_2eh
