// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: TickAttribBidAsk.proto
// Protobuf C++ Version: 5.29.3

#include "TickAttribBidAsk.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {

inline constexpr TickAttribBidAsk::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        bidpastlow_{false},
        askpasthigh_{false} {}

template <typename>
PROTOBUF_CONSTEXPR TickAttribBidAsk::TickAttribBidAsk(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TickAttribBidAskDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TickAttribBidAskDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TickAttribBidAskDefaultTypeInternal() {}
  union {
    TickAttribBidAsk _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TickAttribBidAskDefaultTypeInternal _TickAttribBidAsk_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_TickAttribBidAsk_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_TickAttribBidAsk_2eproto = nullptr;
const ::uint32_t
    TableStruct_TickAttribBidAsk_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protobuf::TickAttribBidAsk, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::TickAttribBidAsk, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::TickAttribBidAsk, _impl_.bidpastlow_),
        PROTOBUF_FIELD_OFFSET(::protobuf::TickAttribBidAsk, _impl_.askpasthigh_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::protobuf::TickAttribBidAsk)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_TickAttribBidAsk_default_instance_._instance,
};
const char descriptor_table_protodef_TickAttribBidAsk_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026TickAttribBidAsk.proto\022\010protobuf\"d\n\020Ti"
    "ckAttribBidAsk\022\027\n\nbidPastLow\030\001 \001(\010H\000\210\001\001\022"
    "\030\n\013askPastHigh\030\002 \001(\010H\001\210\001\001B\r\n\013_bidPastLow"
    "B\016\n\014_askPastHighB@\n\026com.ib.client.protob"
    "ufB\025TickAttribBidAskProto\252\002\016IBApi.protob"
    "ufb\006proto3"
};
static ::absl::once_flag descriptor_table_TickAttribBidAsk_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_TickAttribBidAsk_2eproto = {
    false,
    false,
    210,
    descriptor_table_protodef_TickAttribBidAsk_2eproto,
    "TickAttribBidAsk.proto",
    &descriptor_table_TickAttribBidAsk_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_TickAttribBidAsk_2eproto::offsets,
    file_level_enum_descriptors_TickAttribBidAsk_2eproto,
    file_level_service_descriptors_TickAttribBidAsk_2eproto,
};
namespace protobuf {
// ===================================================================

class TickAttribBidAsk::_Internal {
 public:
  using HasBits =
      decltype(std::declval<TickAttribBidAsk>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TickAttribBidAsk, _impl_._has_bits_);
};

TickAttribBidAsk::TickAttribBidAsk(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.TickAttribBidAsk)
}
TickAttribBidAsk::TickAttribBidAsk(
    ::google::protobuf::Arena* arena, const TickAttribBidAsk& from)
    : TickAttribBidAsk(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE TickAttribBidAsk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void TickAttribBidAsk::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, bidpastlow_),
           0,
           offsetof(Impl_, askpasthigh_) -
               offsetof(Impl_, bidpastlow_) +
               sizeof(Impl_::askpasthigh_));
}
TickAttribBidAsk::~TickAttribBidAsk() {
  // @@protoc_insertion_point(destructor:protobuf.TickAttribBidAsk)
  SharedDtor(*this);
}
inline void TickAttribBidAsk::SharedDtor(MessageLite& self) {
  TickAttribBidAsk& this_ = static_cast<TickAttribBidAsk&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* TickAttribBidAsk::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TickAttribBidAsk(arena);
}
constexpr auto TickAttribBidAsk::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(TickAttribBidAsk),
                                            alignof(TickAttribBidAsk));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TickAttribBidAsk::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TickAttribBidAsk_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TickAttribBidAsk::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TickAttribBidAsk>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TickAttribBidAsk::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TickAttribBidAsk>(), &TickAttribBidAsk::ByteSizeLong,
            &TickAttribBidAsk::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TickAttribBidAsk, _impl_._cached_size_),
        false,
    },
    &TickAttribBidAsk::kDescriptorMethods,
    &descriptor_table_TickAttribBidAsk_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TickAttribBidAsk::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> TickAttribBidAsk::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TickAttribBidAsk, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::TickAttribBidAsk>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional bool askPastHigh = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TickAttribBidAsk, _impl_.askpasthigh_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(TickAttribBidAsk, _impl_.askpasthigh_)}},
    // optional bool bidPastLow = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TickAttribBidAsk, _impl_.bidpastlow_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(TickAttribBidAsk, _impl_.bidpastlow_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bool bidPastLow = 1;
    {PROTOBUF_FIELD_OFFSET(TickAttribBidAsk, _impl_.bidpastlow_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool askPastHigh = 2;
    {PROTOBUF_FIELD_OFFSET(TickAttribBidAsk, _impl_.askpasthigh_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void TickAttribBidAsk::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.TickAttribBidAsk)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.bidpastlow_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.askpasthigh_) -
      reinterpret_cast<char*>(&_impl_.bidpastlow_)) + sizeof(_impl_.askpasthigh_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TickAttribBidAsk::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TickAttribBidAsk& this_ = static_cast<const TickAttribBidAsk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TickAttribBidAsk::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TickAttribBidAsk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protobuf.TickAttribBidAsk)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional bool bidPastLow = 1;
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_bidpastlow(), target);
          }

          // optional bool askPastHigh = 2;
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_askpasthigh(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protobuf.TickAttribBidAsk)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TickAttribBidAsk::ByteSizeLong(const MessageLite& base) {
          const TickAttribBidAsk& this_ = static_cast<const TickAttribBidAsk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TickAttribBidAsk::ByteSizeLong() const {
          const TickAttribBidAsk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protobuf.TickAttribBidAsk)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional bool bidPastLow = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 2;
            }
            // optional bool askPastHigh = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TickAttribBidAsk::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TickAttribBidAsk*>(&to_msg);
  auto& from = static_cast<const TickAttribBidAsk&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.TickAttribBidAsk)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.bidpastlow_ = from._impl_.bidpastlow_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.askpasthigh_ = from._impl_.askpasthigh_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TickAttribBidAsk::CopyFrom(const TickAttribBidAsk& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.TickAttribBidAsk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TickAttribBidAsk::InternalSwap(TickAttribBidAsk* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TickAttribBidAsk, _impl_.askpasthigh_)
      + sizeof(TickAttribBidAsk::_impl_.askpasthigh_)
      - PROTOBUF_FIELD_OFFSET(TickAttribBidAsk, _impl_.bidpastlow_)>(
          reinterpret_cast<char*>(&_impl_.bidpastlow_),
          reinterpret_cast<char*>(&other->_impl_.bidpastlow_));
}

::google::protobuf::Metadata TickAttribBidAsk::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_TickAttribBidAsk_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
