"""
Stage 6 — the measurement instrument.

`PROJECT_STATUS.md` §3: "without it the paper run produces fills nobody diffs
against the backtest, which is the *entire reason to launch*." This is that
diff.

Four questions, in the order they matter:

  1. **Shadow parity.** Replay the session's own recorded bars through the same
     state machine that traded them, with the backtest's bar-granularity fill
     rules, and diff the simulated trades against the real ones. A live
     shortfall is then attributable to *fills* rather than to a coding error —
     `replay.py` already established the state machine and the backtest agree
     (779 = 779 ON-days, max daily P&L difference 0.0), so anything this report
     finds is execution.

  2. **S10/S11.** `PHASE2_PARITY.md` S10 predicts a systematic gap on same-bar
     re-entries specifically, and says paper trading tests it "in the fill
     prices themselves, within days, on the very first ON-days". §5 asks the
     two questions directly and this answers them from `fills` and `quotes`.

  3. **Slippage.** Realised, per fill, against the limit that was resting and
     against the mid at decision time.

  4. **§8 monitoring.** The published baselines computed on live data, with the
     >20% structural-break rule the spec asks for. Baselines are read from
     `phase1/out/monitoring_expectations.csv` rather than re-transcribed — that
     file is regenerated by `parity.py` and re-typing the numbers here would
     create a second source of truth.

**This module is read-only and has no broker.** It imports no `ib_async`, opens
the store without writing to it, and can be run at any time against a database
being written by a live session — SQLite WAL permits the concurrent reader.
Nothing it computes feeds back into a trading decision, by construction:
`store.py`'s header makes the broker the only source of state, and a reporting
tool that could steer the engine would break that.

Run:
    python3 band_lab/live/report.py                     # latest session in the db
    python3 band_lab/live/report.py --session 20260806
    python3 band_lab/live/report.py --weekly            # §8, all sessions
    python3 band_lab/live/report.py --all --csv out/
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Sequence
from zoneinfo import ZoneInfo

_HERE = os.path.dirname(os.path.abspath(__file__))
_BAND_LAB = os.path.dirname(_HERE)
for _p in (_HERE, os.path.join(_BAND_LAB, "phase1")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from replay import replay_session                              # noqa: E402
from sleeve import (                                           # noqa: E402
    LAST_HOLDING_IDX, SleeveConfig, SleeveStateMachine, Trade,
)
from store import Store                                        # noqa: E402
from strategy_core import Bar, session_stats                   # noqa: E402
from spec_constants import (                                   # noqa: E402
    BAR_MINUTES, SESSION_OPEN, TIMEZONE,
)

ET = ZoneInfo(TIMEZONE)

#: §8's rule: "Investigate structural breaks, not noise: a month where fill
#: counts or ON-rates deviate >20% from expectation means the market or the
#: execution has changed, not luck."
STRUCTURAL_BREAK = 0.20

#: §8 says *a month*, and the rule is worthless without that qualifier: on a
#: three-session sample every metric deviates by more than 20% and the report
#: would open every week by crying wolf. Defects 6 and 7 (`PROJECT_STATUS.md`
#: §4.7) were both checks that fired on healthy days and each cost a session —
#: "a safety check that fires on healthy days is not a safety feature".
MIN_SESSIONS_FOR_BREAK = 20

#: The roles `orders.py` writes. "E" is the only buy side; the other three are
#: exits and double as the outcome label.
EXIT_OUTCOME = {"T": "target", "S": "stop", "F": "flatten"}

#: `orders.py:ROLE_FLAT`, transcribed rather than imported for the same reason
#: `EXIT_OUTCOME` is: `orders.py` reaches the broker and this module must not.
ROLE_FLATTEN = "F"

#: A SELL crossing the spread on a penny-wide $145 ETF costs well under a basis
#: point, so a flatten filling this far under the quote *that was standing when
#: it printed* is not the spread — it is a routing or a sizing problem worth a
#: human. Deliberately loose: §4.7's flatten is a market order and is expected
#: to pay something every session, and "a safety check that fires on healthy
#: days is not a safety feature" (defects 6 and 7). This one cannot fire on the
#: market having moved after 15:55, because the quote it compares against is
#: the one at the fill.
FLATTEN_VS_QUOTE_BP = 50.0

#: Quantity tolerance when deciding a round trip has closed. Shares are whole
#: live, but the comparison is written in floats and a fractional residue from
#: a bad row should not silently open a phantom trade.
QTY_EPS = 1e-6


# ------------------------------------------------------------------- helpers
def _fmt(x: Optional[float], nd: int = 2, dash: str = "—") -> str:
    if x is None:
        return dash
    if isinstance(x, float) and x != x:          # NaN
        return dash
    return f"{x:,.{nd}f}"


def _pct(x: Optional[float], nd: int = 1) -> str:
    return "—" if x is None else f"{x * 100:,.{nd}f}%"


def _num(row, key: str) -> Optional[float]:
    """A float from a `daily` row, or None if it is absent or unparseable.

    The daily row is written in three passes (§`store.daily`), so a session
    interrupted between them leaves real NULLs. This file must report that, not
    raise a TypeError in the middle of a post-session review.
    """
    try:
        v = row[key]
    except (KeyError, IndexError):
        return None
    if v is None:
        return None
    try:
        f = float(v)
    except (TypeError, ValueError):
        return None
    return None if f != f else f          # NaN is not a usable input either


def bar_idx_of(ts: str) -> Optional[int]:
    """Bar index for a UTC ISO timestamp, on the §2.1 clock (0 is 09:30 ET).

    Returns None outside the session. This is the same offset arithmetic
    `spec_constants.bar_index` does for a wall-clock string, but starting from
    a stored timestamp — and it is deliberately zone-aware, because the defect
    that cost a whole session (`PROJECT_STATUS.md` §4.6) was a naive local
    time producing `Bar.idx = -36`.
    """
    try:
        dt = datetime.fromisoformat(ts)
    except (TypeError, ValueError):
        return None
    if dt.tzinfo is None:
        return None
    et = dt.astimezone(ET)
    oh, om = (int(v) for v in SESSION_OPEN.split(":"))
    delta = (et.hour * 60 + et.minute) - (oh * 60 + om)
    if delta < 0:
        return None
    return delta // BAR_MINUTES


def session_label(session: str) -> str:
    """`20260806` -> `2026-08-06`; anything else is returned unchanged."""
    if len(session) == 8 and session.isdigit():
        return f"{session[:4]}-{session[4:6]}-{session[6:]}"
    return session


# --------------------------------------------------------------- store reads
def sessions_in(store: Store) -> list[str]:
    return [r["session"] for r in
            store.rows("SELECT DISTINCT session FROM daily ORDER BY session")]


def symbols_in(store: Store, session: str) -> list[str]:
    return [r["symbol"] for r in store.rows(
        "SELECT DISTINCT symbol FROM daily WHERE session=? ORDER BY symbol",
        (session,))]


def daily_row(store: Store, symbol: str, session: str):
    rows = store.rows("SELECT * FROM daily WHERE session=? AND symbol=?",
                      (session, symbol))
    return rows[0] if rows else None


def recorded_bars(store: Store, symbol: str, session: str) -> list[Bar]:
    """The bars the engine actually decided on, from the `bars` table."""
    return [Bar(int(r["bar_idx"]), float(r["open"]), float(r["high"]),
                float(r["low"]), float(r["close"]), float(r["volume"] or 0.0))
            for r in store.session_bars(symbol, session)]


def entry_limits(store: Store, symbol: str, session: str) -> dict[int, float]:
    """bar_idx -> the resting BUY LIMIT price, from the order log.

    Used by the slippage and S10 sections to know what price the engine was
    actually working when a fill arrived.
    """
    out: dict[int, float] = {}
    for r in store.rows(
            "SELECT * FROM orders WHERE session=? AND symbol=? AND role='E' "
            "AND event IN ('placed','modified') ORDER BY ts", (session, symbol)):
        idx = bar_idx_of(r["ts"])
        if idx is not None and r["limit_px"] is not None:
            out[idx] = float(r["limit_px"])
    return out


# ------------------------------------------------- live trade reconstruction
@dataclass
class LiveTrade:
    """One round trip, rebuilt from executions rather than from orders.

    **Executions, not orders, is the load-bearing choice here.** Defect 8
    (`PROJECT_STATUS.md` §4.7) was exactly the mistake of reading one order as
    one fill: IBKR settled 541 shares as 300 + 210 + 31. A report that
    reconstructed trades order-by-order would reproduce the defect it exists to
    detect. Walking executions and closing the trade when the position returns
    to flat is robust to any split.
    """
    entry_bar: Optional[int]
    exit_bar: Optional[int]
    entry_px: float               # quantity-weighted over all entry executions
    exit_px: float                # quantity-weighted over all exit executions
    qty: float
    outcome: str                  # "target" | "stop" | "flatten" | "open"
    n_entry_execs: int = 0
    n_exit_execs: int = 0
    limit_px: Optional[float] = None

    @property
    def ret(self) -> float:
        """The *price* return of the round trip. Not the sleeve's return.

        These differ whenever the entry filled away from the limit it was sized
        off, which §2.4 makes routine: quantity comes from `limit_px` and the
        fill can gap through it. On 2026-08-13 the re-entry was sized off 152.59
        and filled at 146.63 — a 4.0% gap-through — so the position was 4.0%
        smaller than sleeve capital and the sleeve's return was 4.0% smaller
        than this number. Use `ret_on_capital` for anything compared against
        the shadow, the engine's own P&L, or §8.
        """
        return (self.exit_px / self.entry_px - 1.0) if self.entry_px else 0.0

    @property
    def pnl(self) -> float:
        return (self.exit_px - self.entry_px) * self.qty

    def ret_on_capital(self, capital: Optional[float]) -> Optional[float]:
        """`qty x (exit - entry) / sleeve_capital` — what `sleeve.py` books.

        The one definition that is comparable to anything else in the project:
        `SleeveStateMachine.on_exit_fill` accumulates exactly this into
        `sm.pnl`, the engine logs it as the day's `pnl=`, and §8's published
        figures are the backtest's version of it.
        """
        if not capital:
            return None
        return self.pnl / capital


def day_bp(trades: Sequence[LiveTrade],
           capital: Optional[float]) -> tuple[float, bool]:
    """(basis points, comparable). Closed round trips only.

    `comparable` is False when no sleeve capital was recorded and the figure
    falls back to summed price returns — which is *not* the same quantity as
    the shadow's. Returning that silently is how the two sides came to be
    computed differently in the first place, so the caller has to be told.
    """
    closed = [t for t in trades if t.outcome != "open"]
    if capital:
        return 1e4 * sum(t.pnl for t in closed) / capital, True
    return 1e4 * sum(t.ret for t in closed), False


def live_trades(store: Store, symbol: str, session: str) -> list[LiveTrade]:
    """Round trips from the `fills` table, in execution order."""
    limits = entry_limits(store, symbol, session)
    out: list[LiveTrade] = []

    pos = 0.0
    e_notional = e_qty = x_notional = x_qty = 0.0
    e_execs = x_execs = 0
    entry_bar: Optional[int] = None
    exit_bar: Optional[int] = None
    outcome = "open"
    limit_px: Optional[float] = None

    for f in store.session_fills(symbol, session):
        qty = float(f["qty"] or 0.0)
        px = float(f["price"] or 0.0)
        if qty <= 0.0:
            continue
        idx = bar_idx_of(f["ts"])
        buy = (f["side"] == "BOT") or (f["role"] == "E")

        if buy:
            if pos <= QTY_EPS:
                entry_bar = idx
                # The limit that was resting when this entry began. Fall back to
                # the most recent one at or before the fill bar.
                cands = [b for b in limits if idx is None or b <= idx]
                limit_px = limits[max(cands)] if cands else None
            e_notional += qty * px
            e_qty += qty
            e_execs += 1
            pos += qty
        else:
            x_notional += qty * px
            x_qty += qty
            x_execs += 1
            exit_bar = idx
            outcome = EXIT_OUTCOME.get(f["role"] or "", "flatten")
            pos -= qty
            if pos <= QTY_EPS and e_qty > 0.0:
                out.append(LiveTrade(
                    entry_bar=entry_bar, exit_bar=exit_bar,
                    entry_px=e_notional / e_qty, exit_px=x_notional / x_qty,
                    qty=x_qty, outcome=outcome,
                    n_entry_execs=e_execs, n_exit_execs=x_execs,
                    limit_px=limit_px))
                pos = 0.0
                e_notional = e_qty = x_notional = x_qty = 0.0
                e_execs = x_execs = 0
                entry_bar = exit_bar = None
                limit_px = None

    # Still long at the end of the record: the flatten did not complete, or the
    # report is being run mid-session. Either way it must be visible.
    if e_qty > 0.0 and pos > QTY_EPS:
        out.append(LiveTrade(entry_bar=entry_bar, exit_bar=None,
                             entry_px=e_notional / e_qty, exit_px=float("nan"),
                             qty=pos, outcome="open", n_entry_execs=e_execs,
                             n_exit_execs=x_execs, limit_px=limit_px))
    return out


# --------------------------------------------------------------- the shadow
@dataclass
class Shadow:
    """What the backtest books on the same bars, with the same config."""
    trades: list[Trade]
    pnl: float
    fills: int
    stop_outs: int
    ran: bool
    reason: str = ""


def shadow_replay(bars: Sequence[Bar], row) -> Shadow:
    """Drive the recorded bars through the live state machine.

    The gate and filter are **not re-decided**. They are replayed from what the
    engine recorded in `daily`, so this diff isolates the order path. Feature
    arithmetic is checked separately (`feature_parity`), which is the right
    place for it: a feature bug and a fill bug want different fixes and mixing
    them into one number hides both.

    The config is the *live* config — tick rounding on, whole shares, §2.4
    limit-price sizing — for the same reason. The only thing that differs from
    the real session is who decided the fills.
    """
    if row is None:
        return Shadow([], 0.0, 0, 0, False, "no daily row")
    if not row["gate_ok"]:
        return Shadow([], 0.0, 0, 0, False, row["gate_reason"] or "gate_off")
    if not row["filter_ok"]:
        return Shadow([], 0.0, 0, 0, False, row["filter_reason"] or "stood_down")
    if not bars:
        return Shadow([], 0.0, 0, 0, False, "no bars recorded")

    capital = _num(row, "sleeve_capital")
    if capital is None:
        return Shadow([], 0.0, 0, 0, False, "no sleeve_capital recorded")
    missing = [k for k in ("atr5", "or30", "thr80", "pos10")
               if _num(row, k) is None]
    if missing:
        return Shadow([], 0.0, 0, 0, False,
                      f"daily row is missing {', '.join(missing)}")

    cfg = SleeveConfig(symbol=row["symbol"], sleeve_capital=capital)
    sm = SleeveStateMachine(cfg)

    # §2.2's gate is **not re-decided here**, and re-deriving its inputs from
    # the recorded bars is what made this whole section dead on arrival.
    #
    # `SessionStats.is_half_day` is `last bar idx < FLATTEN_IDX`, and
    # FLATTEN_IDX is the 15:55 bar the engine flattens *at* — so a live session
    # never records it, every real day recomputed as a half day, and the shadow
    # refused on 2026-08-10 for both sleeves while the report still printed
    # "shadow and live agree".
    #
    # The recorded gate decision is the evidence. `gate_decision` returns
    # `gate_on` only when both flags were False, so `gate_ok=1` in the daily row
    # *is* the statement that this was a full session which opened on time.
    # Replaying those values reproduces the engine's decision instead of
    # second-guessing it from data the engine never had.
    gate = sm.begin_session(row["session"], _num(row, "atr5"),
                            is_half_day=False, late_open=False)
    if not gate.ok:
        # Only ATR5 can refuse now, so this is a genuine disagreement: the
        # recorded ATR5 does not clear the gate the engine passed on it.
        return Shadow([], 0.0, 0, 0, False,
                      f"shadow gate refused on recorded atr5="
                      f"{_num(row, 'atr5'):.2f}: {gate.reason}")
    filt = sm.apply_morning_filter(_num(row, "or30"), _num(row, "thr80"),
                                   _num(row, "pos10"))
    if not filt.ok:
        return Shadow([], 0.0, 0, 0, False, f"shadow filter refused: {filt.reason}")

    replay_session(list(bars), sm, fill_model="spec")
    return Shadow(sm.trades, sm.pnl, sm.fills, sm.stop_outs, True)


@dataclass
class Coverage:
    """How much of the tradable session the recorded bars actually span.

    The engine flattens *at* FLATTEN_IDX and stops, so on 2026-08-10 it
    recorded 76 bars — idx 0..75 — while `LAST_HOLDING_IDX` is 76. The shadow
    is therefore force-flattened at bar 75 by `replay_session`'s tail rule,
    while the live session went on trading in bar 76. On that session it cost
    the comparison **68 bp on SOXS alone** (233.04 against 301.44 with the full
    session), all of it in the one trade that exited after the record ended.

    A comparison drawn against a truncated record is not wrong so much as
    *unearned*, and the report has to say which it is.
    """
    n_bars: int
    last_idx: Optional[int]
    missing: int

    @property
    def complete(self) -> bool:
        return self.last_idx is not None and self.last_idx >= LAST_HOLDING_IDX


def bar_coverage(bars: Sequence[Bar]) -> Coverage:
    if not bars:
        return Coverage(0, None, LAST_HOLDING_IDX + 1)
    last = max(b.idx for b in bars)
    return Coverage(len(bars), last, max(0, LAST_HOLDING_IDX - last))


# ------------------------------------------------------------ feature parity
@dataclass
class FeatureCheck:
    name: str
    live: Optional[float]
    recomputed: Optional[float]
    tol: float

    @property
    def ok(self) -> bool:
        if self.live is None or self.recomputed is None:
            return False
        return abs(self.live - self.recomputed) <= self.tol


def feature_parity(bars: Sequence[Bar], row) -> list[FeatureCheck]:
    """Recompute §2.1's session quantities from the recorded bars.

    This is the check that would have caught the `America/Los_Angeles` defect
    without costing a session: if the bars were indexed wrongly, the opening
    range recomputed from them will not match the OR30 the engine recorded.
    """
    if not bars or row is None:
        return []
    stats = session_stats(bars)
    def _get(k):
        v = row[k]
        return None if v is None else float(v)
    return [
        FeatureCheck("or30", _get("or30"), stats.or30, 1e-6),
        FeatureCheck("pos10", _get("pos10"), stats.pos10, 1e-6),
    ]


# ------------------------------------------------------------------ slippage
@dataclass
class SlipRow:
    bar: Optional[int]
    role: str
    side: str
    qty: float
    price: float
    limit_px: Optional[float]
    mid: Optional[float]

    #: A buy filling further below its limit than this is not price improvement
    #: — it is evidence the limit was never near the market. §2.5 prices the
    #: entry 1% below a *rolling session high*, so once price has fallen away
    #: from that high the limit is marketable and the fill has nothing to do
    #: with it. SOXL on 2026-08-10: limit 142.02 off a 09:30 high of 143.45,
    #: filled at 135.69, and the report called −445.71 bp "0 adverse".
    GAP_THROUGH_BP = 100.0

    @property
    def gap_through(self) -> bool:
        """Did this fill happen far away from the limit that was resting?"""
        raw = self._raw_vs_limit()
        return raw is not None and raw < -self.GAP_THROUGH_BP

    def _raw_vs_limit(self) -> Optional[float]:
        if self.limit_px in (None, 0):
            return None
        raw = (self.price / self.limit_px - 1.0) * 1e4
        return raw if self.side == "BOT" else -raw

    @property
    def vs_limit(self) -> Optional[float]:
        """Signed, in basis points, positive == worse than the limit.

        A BUY filling above its limit and a SELL filling below it are both
        adverse, so the sign is flipped on the sell side.

        **None for a gap-through.** Comparing the fill to a limit the market
        had already run past measures the distance travelled since the session
        high, not execution quality, and averaging it in buries the fills that
        say something. Those are reported separately, and `vs_mid` — the quote
        while the order was actually working — is the honest execution number.
        """
        raw = self._raw_vs_limit()
        return None if raw is None or self.gap_through else raw

    @property
    def vs_mid(self) -> Optional[float]:
        if self.mid in (None, 0):
            return None
        raw = (self.price / self.mid - 1.0) * 1e4
        return raw if self.side == "BOT" else -raw


def slippage(store: Store, symbol: str, session: str) -> list[SlipRow]:
    limits = entry_limits(store, symbol, session)
    out = []
    for f in store.session_fills(symbol, session):
        idx = bar_idx_of(f["ts"])
        role = f["role"] or "?"
        bid, ask = f["bid"], f["ask"]
        mid = (float(bid) + float(ask)) / 2.0 if bid and ask else None
        lim = None
        if role == "E":
            cands = [b for b in limits if idx is None or b <= idx]
            lim = limits[max(cands)] if cands else None
        out.append(SlipRow(bar=idx, role=role, side=f["side"] or "",
                           qty=float(f["qty"] or 0.0), price=float(f["price"] or 0.0),
                           limit_px=lim, mid=mid))
    return out


# --------------------------------------------------------- the 15:55 flatten
@dataclass
class ExitQuality:
    """Exit executions against the quote that was standing when they printed.

    **The exit side had no measurement at all.** `vs_limit` is None for every
    role but "E" — an exit has no resting entry limit to be graded against — and
    the "honest execution number" filtered to `role == "E"` as well. So a
    session whose whole result turned in its last bar produced a report with no
    line in it about that bar, and the first question anyone asks after such a
    session ("what did the exit cost us?") could not be answered from the
    instrument built to answer exactly that kind of question.

    Every fill already carries a quote: `orders.py:_record_fill` stamps bid/ask
    onto *every* execution regardless of role. Nothing new has to be recorded —
    this only reads what was already there.
    """
    role: str
    n_execs: int
    qty: float
    px: float                       # quantity-weighted over the executions
    vs_mid_bp: Optional[float]      # quantity-weighted; positive == worse


@dataclass
class FlattenCost:
    """What the 15:55 market order cost against the price the backtest books.

    `orders.py:_flatten` sends a **MKT** — §4.7, deliberately not a MOC, because
    §1's first design priority is never holding overnight and a MOC can be
    neither modified nor re-sent when it comes back short. The live exit
    therefore takes whatever the tape gives it from 15:55 onward, while
    `replay_session`'s tail rule books the backtest's flatten at the **close of
    `LAST_HOLDING_IDX`** — the 15:55:00 print, no spread, no delay, no
    uncertainty about when the order actually went out.

    That gap is a real and recurring cost of running the strategy which the
    backtest does not carry, and it belongs in the report next to the shadow it
    explains. On 2026-08-12 SOXL's shadow flattened at 142.99 and the live
    session at 142.15 — 59 bp, most of the day's loss — and the report said
    nothing about it at all.

    **`bp` and `vs_mid_bp` are different quantities and the distinction is the
    whole point.** `bp` is the total: spread plus however far the market
    travelled between 15:55:00 and the fill. `vs_mid_bp` is the spread-crossing
    alone, because it prices the fill against the quote standing when it
    printed. A large `bp` with a small `vs_mid_bp` means the market moved and
    the order was filled fairly; a large `vs_mid_bp` means the execution itself
    was bad. Only the second is a defect.
    """
    qty: float
    live_px: float                  # quantity-weighted over the flatten fills
    ref_px: Optional[float]         # close of LAST_HOLDING_IDX
    n_execs: int
    vs_mid_bp: Optional[float]

    @property
    def bp(self) -> Optional[float]:
        """Signed, positive == the market order beat the backtest's price."""
        if not self.ref_px or not self.live_px:
            return None
        return (self.live_px / self.ref_px - 1.0) * 1e4

    @property
    def dollars(self) -> Optional[float]:
        """Signed dollars on the shares actually flattened.

        The one number here that is not a ratio, and the one a human asks for
        first. It is exact: both prices and the quantity are recorded.
        """
        if self.ref_px is None:
            return None
        return (self.live_px - self.ref_px) * self.qty


def _wavg_vs_mid(rows: Sequence[SlipRow]) -> Optional[float]:
    """Quantity-weighted `vs_mid`, or None when no fill carried a quote.

    Quantity-weighted rather than a plain mean because IBKR splits one order
    across executions of wildly different sizes — a 27-share tail must not
    count the same as the 497 shares it followed.
    """
    num = den = 0.0
    for s in rows:
        if s.vs_mid is None or s.qty <= 0.0:
            continue
        num += s.qty * s.vs_mid
        den += s.qty
    return (num / den) if den else None


def exit_quality(slips: Sequence[SlipRow]) -> list[ExitQuality]:
    """Per-role exit execution, in the order the roles matter."""
    out = []
    for role in ("T", "S", ROLE_FLATTEN, "X"):
        rows = [s for s in slips if s.role == role and s.qty > 0.0]
        if not rows:
            continue
        qty = sum(s.qty for s in rows)
        out.append(ExitQuality(
            role=role, n_execs=len(rows), qty=qty,
            px=sum(s.qty * s.price for s in rows) / qty,
            vs_mid_bp=_wavg_vs_mid(rows)))
    return out


def flatten_cost(slips: Sequence[SlipRow],
                 bars: Sequence[Bar]) -> Optional[FlattenCost]:
    """The 15:55 flatten priced against the bar the backtest exits on.

    None when the session never flattened. A day that ended on a target or a
    stop paid this cost nothing, and printing a zero for it would put a line in
    every report that means nothing on most of them.
    """
    rows = [s for s in slips if s.role == ROLE_FLATTEN and s.qty > 0.0]
    if not rows:
        return None
    qty = sum(s.qty for s in rows)
    ref = next((b.close for b in bars if b.idx == LAST_HOLDING_IDX), None)
    return FlattenCost(qty=qty,
                       live_px=sum(s.qty * s.price for s in rows) / qty,
                       ref_px=ref, n_execs=len(rows),
                       vs_mid_bp=_wavg_vs_mid(rows))


# ------------------------------------------------------------- S10/S11 checks
@dataclass
class FillWithoutQuote:
    """§5 question 1: did a fill occur without the quote reaching the limit?"""
    bar: Optional[int]
    price: float
    limit_px: float
    best_bid_seen: Optional[float]
    n_quotes: int

    @property
    def suspicious(self) -> bool:
        # Only a positive observation counts. With no quotes recorded there is
        # no evidence either way, and the report must not manufacture some —
        # defects 6 and 7 were both checks that fired on absence of evidence.
        return (self.n_quotes > 0 and self.best_bid_seen is not None
                and self.best_bid_seen > self.limit_px)


def fills_without_quotes(store: Store, symbol: str,
                         session: str) -> list[FillWithoutQuote]:
    quotes = store.rows(
        "SELECT * FROM quotes WHERE session=? AND symbol=? ORDER BY ts",
        (session, symbol))
    limits = entry_limits(store, symbol, session)
    out = []
    for f in store.session_fills(symbol, session):
        if (f["role"] or "") != "E":
            continue
        idx = bar_idx_of(f["ts"])
        cands = [b for b in limits if idx is None or b <= idx]
        if not cands:
            continue
        lim = limits[max(cands)]
        seen = [float(q["bid"]) for q in quotes
                if q["bid"] is not None and (bar_idx_of(q["ts"]) or -1) <= (idx or 10**6)]
        out.append(FillWithoutQuote(bar=idx, price=float(f["price"] or 0.0),
                                    limit_px=lim,
                                    best_bid_seen=min(seen) if seen else None,
                                    n_quotes=len(seen)))
    return out


@dataclass
class SameBarReentry:
    """§5 question 2, and the sharpest available test of S10.

    S10's claim is that the 5-minute backtest books a re-entry at a price that
    had already traded *before* the exit it follows. Live, the re-entry order
    is sent after the exit fills, so it can only trade against prints that come
    after it.

    **What this can and cannot prove.** A live re-entry priced below the exit
    it followed is *not* impossible — the market may simply have fallen after
    the exit, which is an ordinary and profitable event. So `live_better` is
    not a defect detector on its own. What isolates S10 is the comparison:
    `shadow_advantage_bp` on events both sources saw, and the count of
    re-entries the shadow books that the live session never had at all.
    """
    bar: int
    prev_exit_px: float
    live_entry_px: Optional[float]
    shadow_entry_px: Optional[float]

    @property
    def live_better(self) -> Optional[bool]:
        """Did the live re-entry get in below the price it had just sold at?

        §5 question 2 asks for this directly. "At or worse" — i.e. False — is
        the answer S10 predicts should dominate.
        """
        if self.live_entry_px is None:
            return None
        return self.live_entry_px < self.prev_exit_px

    @property
    def shadow_better(self) -> Optional[bool]:
        if self.shadow_entry_px is None:
            return None
        return self.shadow_entry_px < self.prev_exit_px

    @property
    def shadow_advantage_bp(self) -> Optional[float]:
        """How much cheaper the backtest got in, on an event both sources saw.

        Positive means the shadow bought below the live fill — the S10
        exposure, measured in the only place it can be measured directly.
        """
        if self.live_entry_px is None or not self.shadow_entry_px:
            return None
        return (self.live_entry_px / self.shadow_entry_px - 1.0) * 1e4


def same_bar_reentries(live: Sequence[LiveTrade],
                       shadow: Sequence[Trade]) -> list[SameBarReentry]:
    """Re-entries that began in the bar the previous trade exited in."""
    out: list[SameBarReentry] = []

    def _pairs_live():
        for a, b in zip(live, live[1:]):
            if a.exit_bar is not None and b.entry_bar == a.exit_bar:
                yield a.exit_bar, a.exit_px, b.entry_px
    def _pairs_shadow():
        for a, b in zip(shadow, shadow[1:]):
            if b.entry_bar == a.exit_bar:
                yield a.exit_bar, a.exit_px, b.entry_px

    shadow_by_bar = {bar: (xpx, epx) for bar, xpx, epx in _pairs_shadow()}
    for bar, xpx, epx in _pairs_live():
        s = shadow_by_bar.pop(bar, None)
        out.append(SameBarReentry(bar=bar, prev_exit_px=xpx, live_entry_px=epx,
                                  shadow_entry_px=s[1] if s else None))
    # Shadow re-entries the live session never had — the S10 population that
    # simply does not exist in reality. These are the most important rows.
    for bar, (xpx, epx) in sorted(shadow_by_bar.items()):
        out.append(SameBarReentry(bar=bar, prev_exit_px=xpx,
                                  live_entry_px=None, shadow_entry_px=epx))
    return sorted(out, key=lambda r: r.bar)


# ------------------------------------------------------------ §8 monitoring
#: V20's corrected baselines, read in preference to the `spec` file below.
#: Kept separate rather than overwriting `monitoring_expectations.csv` because
#: `parity.py` regenerates that file under `spec` on every run — a corrected
#: value written there is reverted by the next Phase 1 run, silently, in the one
#: number the daily report measures live against.
V20_BASELINES = ("v2_dev", "out", "v20_corrected_baselines.csv")
SPEC_BASELINES = ("phase1", "out", "monitoring_expectations.csv")


def load_baselines(root: str = _BAND_LAB) -> dict[tuple[str, str], float]:
    """§8's baselines: V20's corrected values layered over the `spec` file.

    V20 established that `spec` prices a same-bar re-entry at a price that
    traded *before* the exit it followed, and that live never gets that fill:
    ten such trades appear in the backtest and none in thirteen live
    sleeve-sessions. Comparing live against a baseline built on unavailable
    fills measures the simulator, not the strategy.

    The two files are layered rather than swapped because V20 corrects the
    metrics a fill model can move and no others — `ON_day_rate_%` comes off the
    gate, which is computed from prior sessions, so it still comes from `spec`.
    """
    out: dict[tuple[str, str], float] = {}
    for parts in (SPEC_BASELINES, V20_BASELINES):       # later wins
        path = os.path.join(root, *parts)
        if not os.path.exists(path):
            continue
        with open(path, newline="", encoding="utf-8") as fh:
            for r in csv.DictReader(fh):
                try:
                    out[(r["sleeve"], r["metric"])] = float(r["measured"])
                except (KeyError, TypeError, ValueError):
                    continue
    return out


def baseline_source(root: str = _BAND_LAB) -> str:
    """Which baselines a report is using. Printed, never inferred."""
    return ("V20-corrected (no_better fill model)"
            if os.path.exists(os.path.join(root, *V20_BASELINES))
            else "spec (UNCORRECTED — V20 has not been run)")


@dataclass
class Weekly:
    symbol: str
    sessions: int = 0
    on_days: int = 0
    fills: int = 0
    outcomes: dict = field(default_factory=dict)
    day_returns: list[float] = field(default_factory=list)

    @property
    def on_rate(self) -> Optional[float]:
        return 100.0 * self.on_days / self.sessions if self.sessions else None

    @property
    def fills_per_on_day(self) -> Optional[float]:
        return self.fills / self.on_days if self.on_days else None

    @property
    def gross_bp(self) -> Optional[float]:
        if not self.day_returns:
            return None
        return 1e4 * sum(self.day_returns) / len(self.day_returns)

    @property
    def worst_day(self) -> Optional[float]:
        return 100.0 * min(self.day_returns) if self.day_returns else None

    def outcome_pct(self, name: str) -> Optional[float]:
        total = sum(self.outcomes.values())
        return 100.0 * self.outcomes.get(name, 0) / total if total else None


def weekly(store: Store, symbols: Optional[Sequence[str]] = None,
           sessions: Optional[Sequence[str]] = None) -> dict[str, Weekly]:
    sessions = list(sessions or sessions_in(store))
    acc: dict[str, Weekly] = {}
    for s in sessions:
        for sym in (symbols or symbols_in(store, s)):
            row = daily_row(store, sym, s)
            if row is None:
                continue
            w = acc.setdefault(sym, Weekly(sym))
            w.sessions += 1
            traded = bool(row["gate_ok"]) and bool(row["filter_ok"])
            if not traded:
                continue
            w.on_days += 1
            trades = live_trades(store, sym, s)
            w.fills += len(trades)
            # §8's baselines are the backtest's `sm.pnl`, so the live series
            # compared against them has to be the same quantity — see the note
            # in `print_session_report`. Summing price returns here made
            # `gross_bp_per_ON_day` and `worst_day_%` drift from the engine's
            # own numbers by the gap-through depth of each entry.
            bp, _ = day_bp(trades, _num(row, "sleeve_capital"))
            w.day_returns.append(bp / 1e4)
            for t in trades:
                w.outcomes[t.outcome] = w.outcomes.get(t.outcome, 0) + 1
    return acc


# ------------------------------------------------------------------ printing
def _rule(title: str = "", ch: str = "=", width: int = 78) -> str:
    return ch * width if not title else f"{title} ".ljust(width, ch)


def print_session_report(store: Store, session: str,
                         symbols: Optional[Sequence[str]] = None) -> int:
    """The daily report. Returns the number of findings that need a human."""
    findings = 0
    compared: list[str] = []                    # traded, shadow ran, bars complete
    unverified: list[tuple[str, str]] = []      # traded, shadow did not run
    truncated: list[tuple[str, Coverage]] = []  # traded, shadow ran, bars short
    syms = list(symbols or symbols_in(store, session))
    print(_rule())
    print(f"SESSION {session_label(session)} — shadow parity and fill quality")
    print(_rule())
    if not syms:
        print("\nNo sleeves recorded for this session.")
        return 0

    for sym in syms:
        row = daily_row(store, sym, session)
        bars = recorded_bars(store, sym, session)
        live = live_trades(store, sym, session)
        sh = shadow_replay(bars, row)

        print(f"\n{_rule(sym, '-')}")
        if row is not None:
            print(f"  gate    {'ON ' if row['gate_ok'] else 'OFF'}  "
                  f"{row['gate_reason'] or '':<32} atr5={_fmt(row['atr5'])}")
            print(f"  filter  {'ON ' if row['filter_ok'] else 'OFF'}  "
                  f"{row['filter_reason'] or '':<32} "
                  f"or30={_fmt(row['or30'])} thr80={_fmt(row['thr80'])} "
                  f"pos10={_fmt(row['pos10'], 3)}")
            print(f"  capital {_fmt(row['sleeve_capital'], 0)}   bars recorded: {len(bars)}")

        # --- 1. feature parity
        checks = feature_parity(bars, row)
        for c in checks:
            if not c.ok:
                findings += 1
                print(f"  [FINDING] {c.name}: engine recorded {_fmt(c.live, 4)}, "
                      f"recomputed from the recorded bars {_fmt(c.recomputed, 4)}")

        # --- 2. shadow parity
        #
        # A sleeve the engine actually traded and the shadow did not reproduce
        # is a FINDING, not a footnote. On 2026-08-10 both sleeves landed here
        # and the report still signed off "shadow and live agree" — the failure
        # this section exists to make impossible.
        traded = bool(row is not None and row["gate_ok"] and row["filter_ok"])
        cov = bar_coverage(bars)
        if traded and not sh.ran:
            findings += 1
            unverified.append((sym, sh.reason))
            print(f"\n  [FINDING] shadow: did not run — {sh.reason}")
            print("            this sleeve traded, so NOTHING was compared for it")
        else:
            print(f"\n  shadow: {'ran' if sh.ran else 'did not run — ' + sh.reason}")
        if traded and sh.ran:
            if cov.complete:
                compared.append(sym)
            else:
                truncated.append((sym, cov))
                print(f"  [WARN] bars recorded end at idx {cov.last_idx}, "
                      f"{cov.missing} short of the last holding bar "
                      f"({LAST_HOLDING_IDX}) — the shadow is force-flattened "
                      f"early and understates itself")
        if sh.ran or live:
            print(f"    {'':<4} {'LIVE':<38}{'SHADOW (backtest fills)':<38}")
            print(f"    {'#':<4} {'bars':<9} {'entry':>8} {'exit':>8}  {'out':<9}"
                  f"{'bars':<9} {'entry':>8} {'exit':>8}  {'out':<9}")
            for i in range(max(len(live), len(sh.trades))):
                lt = live[i] if i < len(live) else None
                st = sh.trades[i] if i < len(sh.trades) else None
                blank = f"{'—':<9} {'—':>8} {'—':>8}  {'—':<9}"
                lc = (f"{str(lt.entry_bar) + '>' + str(lt.exit_bar):<9} "
                      f"{_fmt(lt.entry_px):>8} {_fmt(lt.exit_px):>8}  "
                      f"{lt.outcome:<9}") if lt else blank
                sc = (f"{str(st.entry_bar) + '>' + str(st.exit_bar):<9} "
                      f"{_fmt(st.entry_px):>8} {_fmt(st.exit_px):>8}  "
                      f"{st.outcome:<9}") if st else blank
                print(f"    {i+1:<4} {lc}{sc}")

            # **Both sides must be the same quantity, and for a while they were
            # not.** The shadow is `sm.pnl` — `qty x (exit - entry) / capital`,
            # accumulated by `sleeve.py:on_exit_fill`. The live side summed
            # `exit / entry - 1` instead, on a comment asserting those were the
            # same thing. They coincide only when `qty x entry == capital`,
            # which §2.4 breaks by design: quantity is sized off `limit_px` and
            # the fill may gap through it.
            #
            # On 2026-08-13 the re-entry gapped 4.0% through its limit, so the
            # two definitions differed by 7.1 bp and the report announced a
            # 0.75 bp gap where the like-for-like figure was 7.85 bp — while
            # the engine's own EOD line said `pnl=-555.6bp`, agreeing with the
            # shadow's definition and not with the report's. A parity report
            # whose headline disagrees with the engine it is auditing is worse
            # than no report. The error scales with gap-through depth, so it is
            # largest exactly on the days worth reading closely.
            cap = _num(row, "sleeve_capital") if row is not None else None
            lbp, comparable = day_bp(live, cap)
            sbp = 1e4 * sh.pnl
            print(f"\n    trades   live {len(live):<3}  shadow {len(sh.trades)}")
            if comparable:
                print(f"    bp/day   live {_fmt(lbp):<7}  shadow {_fmt(sbp):<7}  "
                      f"gap {_fmt(lbp - sbp)}   "
                      f"(qty x (exit-entry) / sleeve capital, both sides)")
            else:
                findings += 1
                print(f"    bp/day   live {_fmt(lbp):<7}  shadow {_fmt(sbp):<7}")
                print("    [FINDING] no sleeve_capital recorded, so the live "
                      "figure is summed price returns and the shadow is not — "
                      "these two numbers are NOT comparable and no gap is shown")
            if len(live) != len(sh.trades) and sh.ran:
                findings += 1
                print("    [FINDING] trade-count mismatch: the fill models "
                      "disagree on how many round trips this session held")

        # --- multi-execution entries (defect 8's signature)
        multi = [t for t in live if t.n_entry_execs > 1]
        if multi:
            print(f"\n  entries settled in multiple executions: {len(multi)} "
                  f"({', '.join(str(t.n_entry_execs) for t in multi)}) — "
                  f"the bracket must have covered the whole position each time")

        # --- 3. S10/S11
        q1 = [f for f in fills_without_quotes(store, sym, session) if f.suspicious]
        if q1:
            findings += len(q1)
            print(f"\n  [FINDING] {len(q1)} entry fill(s) with no recorded quote "
                  f"reaching the limit:")
            for f in q1:
                print(f"      bar {f.bar}: filled {_fmt(f.price)} on a limit of "
                      f"{_fmt(f.limit_px)}, best bid seen {_fmt(f.best_bid_seen)} "
                      f"over {f.n_quotes} quotes")

        reentries = same_bar_reentries(live, sh.trades)
        if reentries:
            print("\n  same-bar re-entries (S10 — the sharpest available test):")
            for r in reentries:
                adv = r.shadow_advantage_bp
                print(f"      bar {r.bar}: prev exit {_fmt(r.prev_exit_px)}  "
                      f"live {_fmt(r.live_entry_px)}"
                      f"{' (below the exit)' if r.live_better else ''}  "
                      f"shadow {_fmt(r.shadow_entry_px)}"
                      f"{' (below the exit)' if r.shadow_better else ''}"
                      + (f"  shadow advantage {_fmt(adv)} bp" if adv else ""))

            both = [r for r in reentries if r.shadow_advantage_bp is not None]
            if both:
                mean_adv = sum(r.shadow_advantage_bp for r in both) / len(both)
                print(f"      mean shadow advantage over {len(both)} shared "
                      f"event(s): {_fmt(mean_adv)} bp")
            # §5 question 2, answered directly.
            answered = [r for r in reentries if r.live_better is not None]
            if answered:
                worse = sum(1 for r in answered if not r.live_better)
                print(f"      §5 Q2 — live re-entry at or worse than the price "
                      f"just sold: {worse} of {len(answered)}")
            ghosts = [r for r in reentries if r.live_entry_px is None]
            if ghosts:
                print(f"      {len(ghosts)} re-entry(ies) the backtest books that "
                      f"the live session never had — the S10 population")

        # --- 4. slippage
        slips = slippage(store, sym, session)
        graded = [s for s in slips if s.vs_limit is not None]
        if graded:
            avg = sum(s.vs_limit for s in graded) / len(graded)
            worse = sum(1 for s in graded if s.vs_limit > 0)
            print(f"\n  slippage vs the resting limit: {len(graded)} entry "
                  f"execution(s), mean {_fmt(avg)} bp, {worse} adverse "
                  f"(positive == worse than the limit)")
        gaps = [s for s in slips if s.gap_through]
        if gaps:
            worst = min(s._raw_vs_limit() for s in gaps)
            print(f"\n  gap-through entries: {len(gaps)} execution(s) filled far "
                  f"below the resting limit (worst {_fmt(worst)} bp)")
            print(f"      Not slippage. §2.5 prices the entry 1% under a rolling "
                  f"session high, so once price falls away from that high the "
                  f"limit is marketable and the fill is unrelated to it.")
            print(f"      The backtest models this — it fills a gap-through at "
                  f"the bar open — so the shadow above is the check that matters, "
                  f"not this number.")
        mids = [s for s in slips if s.role == "E" and s.vs_mid is not None]
        if mids:
            m = sum(s.vs_mid for s in mids) / len(mids)
            print(f"\n  entry fills vs the quote while the order worked: "
                  f"{len(mids)} execution(s), mean {_fmt(m)} bp "
                  f"(the honest execution number)")

        # --- 5. the exit side
        #
        # Everything above this line grades entries. A session can lose its
        # whole result in the exit — 2026-08-12 lost 59 bp of 152 in the 15:55
        # flatten — and the report used to have no line about it, which made the
        # instrument unable to answer the first question asked of it that day.
        exits = exit_quality(slips)
        if exits:
            print("\n  exit fills vs the quote standing when they printed:")
            for e in exits:
                print(f"      {EXIT_OUTCOME.get(e.role, e.role):<9} "
                      f"{e.n_execs:>3} execution(s)  {e.qty:>7,.0f} sh  "
                      f"@ {_fmt(e.px):>9}  {_fmt(e.vs_mid_bp):>8} bp"
                      f"  (positive == worse)")

        fc = flatten_cost(slips, bars)
        if fc is not None:
            print(f"\n  the 15:55 flatten — a MARKET order (§4.7: MKT, not MOC, "
                  f"because §1 puts being flat above the fill price):")
            print(f"      {fc.qty:,.0f} share(s) in {fc.n_execs} execution(s), "
                  f"vwap {_fmt(fc.live_px)}")
            if fc.ref_px is None:
                print(f"      bar {LAST_HOLDING_IDX} was not recorded, so there "
                      f"is nothing to price the flatten against — "
                      f"`record_session_tail` is what backfills it")
            else:
                print(f"      the backtest exits this trade at the bar "
                      f"{LAST_HOLDING_IDX} close ({_fmt(fc.ref_px)}), free and "
                      f"on time; live paid {_fmt(fc.bp)} bp = "
                      f"{_fmt(fc.dollars)} against that")
            if fc.vs_mid_bp is None:
                print("      no quote was recorded beside the flatten fills, so "
                      "the spread and the market's move cannot be separated")
            else:
                print(f"      of which spread-crossing is {_fmt(fc.vs_mid_bp)} "
                      f"bp — the fill against the quote at the moment it "
                      f"printed. The rest is the market moving between 15:55 "
                      f"and the fill, which no order type would have avoided.")
                if fc.vs_mid_bp > FLATTEN_VS_QUOTE_BP:
                    findings += 1
                    print(f"      [FINDING] {_fmt(fc.vs_mid_bp)} bp against the "
                          f"standing quote is not a spread on a liquid ETF — "
                          f"this is the execution itself, not the market.")

    # ------------------------------------------------------------- sign-off
    #
    # This line is the one a human reads when they read nothing else, so it may
    # only claim what was actually established. The 2026-08-10 report printed
    # "Shadow and live agree" having compared nothing at all on either sleeve.
    # Every clause below is now conditioned on a comparison having happened.
    print(f"\n{_rule()}")
    if findings:
        print(f"{findings} finding(s) needing a human.")
    if unverified:
        print("NOT VERIFIED — the shadow did not run on: "
              + ", ".join(f"{s} ({why})" for s, why in unverified))
        print("  No agreement is claimed for those sleeves. Nothing was compared.")
    if truncated:
        print("PARTIALLY VERIFIED — bar record ends before the last holding bar on: "
              + ", ".join(f"{s} (short {c.missing})" for s, c in truncated))
        print("  Those shadows force-flatten early, so the live-vs-shadow gap on "
              "them is overstated in live's favour.")
    if compared and not findings and not truncated:
        print(f"No findings. Shadow and live agree on "
              f"{', '.join(compared)}, over the complete tradable session.")
    elif not findings and not unverified and not truncated:
        # Nothing traded — a real and ordinary outcome, and not an agreement.
        print("No findings. No sleeve traded, so there was nothing to compare.")
    print(_rule())
    return findings


def print_weekly_report(store: Store, symbols: Optional[Sequence[str]] = None,
                        sessions: Optional[Sequence[str]] = None) -> int:
    """§8's comparison against the published baselines. Returns break count."""
    base = load_baselines()
    acc = weekly(store, symbols, sessions)
    breaks = 0
    print(_rule())
    print("§8 MONITORING — live against the published baselines")
    print(_rule())
    print(f"  baselines: {baseline_source()}")
    if not base:
        print("\n  phase1/out/monitoring_expectations.csv not found — run "
              "`python3 band_lab/phase1/parity.py` to regenerate it.")
    for sym, w in sorted(acc.items()):
        print(f"\n{_rule(sym, '-')}")
        print(f"  {w.sessions} session(s), {w.on_days} ON-day(s), "
              f"{w.fills} round trip(s)")
        rows = [
            ("fills_per_ON_day", w.fills_per_on_day, 2),
            ("ON_day_rate_%", w.on_rate, 1),
            ("target_%", w.outcome_pct("target"), 1),
            ("stop_%", w.outcome_pct("stop"), 1),
            ("flatten_%", w.outcome_pct("flatten"), 1),
            ("gross_bp_per_ON_day", w.gross_bp, 1),
            ("worst_day_%", w.worst_day, 2),
        ]
        print(f"    {'metric':<22} {'live':>10} {'§8':>10} {'deviation':>12}")
        for name, val, nd in rows:
            exp = base.get((sym, name))
            dev = None
            if val is not None and exp not in (None, 0):
                dev = (val - exp) / abs(exp)
            flag = ""
            # §8: the >20% rule applies to fill counts and ON-rates. bp figures
            # are far too noisy on a short window for a deviation to mean
            # anything, and PHASE2_PARITY S11 says to expect 54-64% of the
            # published number anyway — flagging that would be noise by design.
            if (dev is not None and w.sessions >= MIN_SESSIONS_FOR_BREAK
                    and name in ("fills_per_ON_day", "ON_day_rate_%")
                    and abs(dev) > STRUCTURAL_BREAK):
                flag, breaks = "  <-- STRUCTURAL", breaks + 1
            print(f"    {name:<22} {_fmt(val, nd):>10} {_fmt(exp, nd):>10} "
                  f"{_pct(dev) if dev is not None else '—':>12}{flag}")

        if w.sessions < MIN_SESSIONS_FOR_BREAK:
            print(f"\n    {w.sessions} session(s) — below the "
                  f"{MIN_SESSIONS_FOR_BREAK} §8's monthly rule needs, so no "
                  f"deviation above is flagged. A single week proves nothing.")
    print(f"\n{_rule()}")
    print(f"{breaks} structural break(s) — investigate." if breaks
          else "No structural break against §8 on the >20% rule.")
    print(_rule())
    return breaks


# ------------------------------------------------------------------ CSV out
def write_csvs(store: Store, outdir: str, session: str,
               symbols: Optional[Sequence[str]] = None) -> list[str]:
    os.makedirs(outdir, exist_ok=True)
    written = []
    trade_path = os.path.join(outdir, f"parity_{session}.csv")
    with open(trade_path, "w", newline="", encoding="utf-8") as fh:
        wr = csv.writer(fh)
        wr.writerow(["session", "symbol", "n", "src", "entry_bar", "exit_bar",
                     "entry_px", "exit_px", "qty", "outcome", "ret_bp"])
        for sym in (symbols or symbols_in(store, session)):
            row = daily_row(store, sym, session)
            bars = recorded_bars(store, sym, session)
            for i, t in enumerate(live_trades(store, sym, session), 1):
                wr.writerow([session, sym, i, "live", t.entry_bar, t.exit_bar,
                             f"{t.entry_px:.4f}", f"{t.exit_px:.4f}", t.qty,
                             t.outcome, f"{t.ret * 1e4:.2f}"])
            for i, t in enumerate(shadow_replay(bars, row).trades, 1):
                wr.writerow([session, sym, i, "shadow", t.entry_bar, t.exit_bar,
                             f"{t.entry_px:.4f}", f"{t.exit_px:.4f}", t.qty,
                             t.outcome, f"{t.ret * 1e4:.2f}"])
    written.append(trade_path)

    slip_path = os.path.join(outdir, f"slippage_{session}.csv")
    with open(slip_path, "w", newline="", encoding="utf-8") as fh:
        wr = csv.writer(fh)
        wr.writerow(["session", "symbol", "bar", "role", "side", "qty", "price",
                     "limit_px", "mid", "vs_limit_bp", "vs_mid_bp"])
        for sym in (symbols or symbols_in(store, session)):
            for s in slippage(store, sym, session):
                wr.writerow([session, sym, s.bar, s.role, s.side, s.qty,
                             f"{s.price:.4f}",
                             "" if s.limit_px is None else f"{s.limit_px:.4f}",
                             "" if s.mid is None else f"{s.mid:.4f}",
                             "" if s.vs_limit is None else f"{s.vs_limit:.2f}",
                             "" if s.vs_mid is None else f"{s.vs_mid:.2f}"])
    written.append(slip_path)
    return written


# ---------------------------------------------------------------------- CLI
def default_db() -> str:
    return os.path.join(_HERE, "out", "live.db")


def main(argv: Optional[Sequence[str]] = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[1],
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--db", default=default_db(), help="path to live.db")
    p.add_argument("--session", help="YYYYMMDD (default: the latest in the db)")
    p.add_argument("--symbol", action="append", dest="symbols",
                   help="restrict to a sleeve; repeatable")
    p.add_argument("--weekly", action="store_true", help="the §8 comparison")
    p.add_argument("--all", action="store_true", help="every session, then §8")
    p.add_argument("--since", metavar="YYYYMMDD",
                   help="ignore sessions before this one. §8's baselines "
                        "describe a fixed strategy, so a window that spans a "
                        "change to the engine compares live against a version "
                        "of itself that no longer exists")
    p.add_argument("--csv", metavar="DIR", help="also write the per-trade CSVs")
    a = p.parse_args(argv)

    if not os.path.exists(a.db):
        print(f"no database at {a.db}\n"
              f"The engine writes it at `live/out/live.db`; pass --db if yours "
              f"is elsewhere.", file=sys.stderr)
        return 2

    store = Store(a.db)
    try:
        all_sessions = sessions_in(store)
        if not all_sessions:
            print("The database has no sessions yet — nothing to report on.")
            return 0

        if a.since:
            kept = [s for s in all_sessions if s >= a.since]
            if not kept:
                print(f"No sessions on or after {a.since}. The database holds "
                      f"{all_sessions[0]} to {all_sessions[-1]}.", file=sys.stderr)
                return 2
            # Say what was dropped. A §8 table that silently covers a subset
            # reads exactly like one that covers everything, and §4.7's rule
            # cuts both ways: a number that does not state its own window is
            # not a measurement.
            print(f"Window: {kept[0]} to {kept[-1]} — "
                  f"{len(all_sessions) - len(kept)} earlier session(s) excluded "
                  f"by --since {a.since}.\n")
            all_sessions = kept

        findings = 0
        if a.weekly and not a.all:
            return 1 if print_weekly_report(store, a.symbols,
                                            all_sessions) else 0

        targets = all_sessions if a.all else [a.session or all_sessions[-1]]
        for s in targets:
            if s not in all_sessions:
                print(f"session {s} is not in the database. Available: "
                      f"{', '.join(all_sessions[-10:])}", file=sys.stderr)
                return 2
            findings += print_session_report(store, s, a.symbols)
            if a.csv:
                for path in write_csvs(store, a.csv, s, a.symbols):
                    print(f"  wrote {path}")
            print()

        if a.all:
            findings += print_weekly_report(store, a.symbols, all_sessions)
        return 1 if findings else 0
    finally:
        store.close()


if __name__ == "__main__":
    raise SystemExit(main())
