"""
Stage 6 — the measurement instrument.

`PROJECT_STATUS.md` §3: "without it the paper run produces fills nobody diffs
against the backtest, which is the *entire reason to launch*." This is that
diff.

Four questions, in the order they matter:

  1. **Shadow parity.** Replay the session's own recorded bars through the same
     state machine that traded them, with the backtest's bar-granularity fill
     rules, and diff the simulated trades against the real ones. A live
     shortfall is then attributable to *fills* rather than to a coding error —
     `replay.py` already established the state machine and the backtest agree
     (779 = 779 ON-days, max daily P&L difference 0.0), so anything this report
     finds is execution.

  2. **S10/S11.** `PHASE2_PARITY.md` S10 predicts a systematic gap on same-bar
     re-entries specifically, and says paper trading tests it "in the fill
     prices themselves, within days, on the very first ON-days". §5 asks the
     two questions directly and this answers them from `fills` and `quotes`.

  3. **Slippage.** Realised, per fill, against the limit that was resting and
     against the mid at decision time.

  4. **§8 monitoring.** The published baselines computed on live data, with the
     >20% structural-break rule the spec asks for. Baselines are read from
     `phase1/out/monitoring_expectations.csv` rather than re-transcribed — that
     file is regenerated by `parity.py` and re-typing the numbers here would
     create a second source of truth.

**This module is read-only and has no broker.** It imports no `ib_async`, opens
the store without writing to it, and can be run at any time against a database
being written by a live session — SQLite WAL permits the concurrent reader.
Nothing it computes feeds back into a trading decision, by construction:
`store.py`'s header makes the broker the only source of state, and a reporting
tool that could steer the engine would break that.

Run:
    python3 band_lab/live/report.py                     # latest session in the db
    python3 band_lab/live/report.py --session 20260806
    python3 band_lab/live/report.py --weekly            # §8, all sessions
    python3 band_lab/live/report.py --all --csv out/
"""

from __future__ import annotations

import argparse
import csv
import os
import sys
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Sequence
from zoneinfo import ZoneInfo

_HERE = os.path.dirname(os.path.abspath(__file__))
_BAND_LAB = os.path.dirname(_HERE)
for _p in (_HERE, os.path.join(_BAND_LAB, "phase1")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from replay import replay_session                              # noqa: E402
from sleeve import SleeveConfig, SleeveStateMachine, Trade     # noqa: E402
from store import Store                                        # noqa: E402
from strategy_core import Bar, session_stats                   # noqa: E402
from spec_constants import (                                   # noqa: E402
    BAR_MINUTES, SESSION_OPEN, TIMEZONE,
)

ET = ZoneInfo(TIMEZONE)

#: §8's rule: "Investigate structural breaks, not noise: a month where fill
#: counts or ON-rates deviate >20% from expectation means the market or the
#: execution has changed, not luck."
STRUCTURAL_BREAK = 0.20

#: §8 says *a month*, and the rule is worthless without that qualifier: on a
#: three-session sample every metric deviates by more than 20% and the report
#: would open every week by crying wolf. Defects 6 and 7 (`PROJECT_STATUS.md`
#: §4.7) were both checks that fired on healthy days and each cost a session —
#: "a safety check that fires on healthy days is not a safety feature".
MIN_SESSIONS_FOR_BREAK = 20

#: The roles `orders.py` writes. "E" is the only buy side; the other three are
#: exits and double as the outcome label.
EXIT_OUTCOME = {"T": "target", "S": "stop", "F": "flatten"}

#: Quantity tolerance when deciding a round trip has closed. Shares are whole
#: live, but the comparison is written in floats and a fractional residue from
#: a bad row should not silently open a phantom trade.
QTY_EPS = 1e-6


# ------------------------------------------------------------------- helpers
def _fmt(x: Optional[float], nd: int = 2, dash: str = "—") -> str:
    if x is None:
        return dash
    if isinstance(x, float) and x != x:          # NaN
        return dash
    return f"{x:,.{nd}f}"


def _pct(x: Optional[float], nd: int = 1) -> str:
    return "—" if x is None else f"{x * 100:,.{nd}f}%"


def bar_idx_of(ts: str) -> Optional[int]:
    """Bar index for a UTC ISO timestamp, on the §2.1 clock (0 is 09:30 ET).

    Returns None outside the session. This is the same offset arithmetic
    `spec_constants.bar_index` does for a wall-clock string, but starting from
    a stored timestamp — and it is deliberately zone-aware, because the defect
    that cost a whole session (`PROJECT_STATUS.md` §4.6) was a naive local
    time producing `Bar.idx = -36`.
    """
    try:
        dt = datetime.fromisoformat(ts)
    except (TypeError, ValueError):
        return None
    if dt.tzinfo is None:
        return None
    et = dt.astimezone(ET)
    oh, om = (int(v) for v in SESSION_OPEN.split(":"))
    delta = (et.hour * 60 + et.minute) - (oh * 60 + om)
    if delta < 0:
        return None
    return delta // BAR_MINUTES


def session_label(session: str) -> str:
    """`20260806` -> `2026-08-06`; anything else is returned unchanged."""
    if len(session) == 8 and session.isdigit():
        return f"{session[:4]}-{session[4:6]}-{session[6:]}"
    return session


# --------------------------------------------------------------- store reads
def sessions_in(store: Store) -> list[str]:
    return [r["session"] for r in
            store.rows("SELECT DISTINCT session FROM daily ORDER BY session")]


def symbols_in(store: Store, session: str) -> list[str]:
    return [r["symbol"] for r in store.rows(
        "SELECT DISTINCT symbol FROM daily WHERE session=? ORDER BY symbol",
        (session,))]


def daily_row(store: Store, symbol: str, session: str):
    rows = store.rows("SELECT * FROM daily WHERE session=? AND symbol=?",
                      (session, symbol))
    return rows[0] if rows else None


def recorded_bars(store: Store, symbol: str, session: str) -> list[Bar]:
    """The bars the engine actually decided on, from the `bars` table."""
    return [Bar(int(r["bar_idx"]), float(r["open"]), float(r["high"]),
                float(r["low"]), float(r["close"]), float(r["volume"] or 0.0))
            for r in store.session_bars(symbol, session)]


def entry_limits(store: Store, symbol: str, session: str) -> dict[int, float]:
    """bar_idx -> the resting BUY LIMIT price, from the order log.

    Used by the slippage and S10 sections to know what price the engine was
    actually working when a fill arrived.
    """
    out: dict[int, float] = {}
    for r in store.rows(
            "SELECT * FROM orders WHERE session=? AND symbol=? AND role='E' "
            "AND event IN ('placed','modified') ORDER BY ts", (session, symbol)):
        idx = bar_idx_of(r["ts"])
        if idx is not None and r["limit_px"] is not None:
            out[idx] = float(r["limit_px"])
    return out


# ------------------------------------------------- live trade reconstruction
@dataclass
class LiveTrade:
    """One round trip, rebuilt from executions rather than from orders.

    **Executions, not orders, is the load-bearing choice here.** Defect 8
    (`PROJECT_STATUS.md` §4.7) was exactly the mistake of reading one order as
    one fill: IBKR settled 541 shares as 300 + 210 + 31. A report that
    reconstructed trades order-by-order would reproduce the defect it exists to
    detect. Walking executions and closing the trade when the position returns
    to flat is robust to any split.
    """
    entry_bar: Optional[int]
    exit_bar: Optional[int]
    entry_px: float               # quantity-weighted over all entry executions
    exit_px: float                # quantity-weighted over all exit executions
    qty: float
    outcome: str                  # "target" | "stop" | "flatten" | "open"
    n_entry_execs: int = 0
    n_exit_execs: int = 0
    limit_px: Optional[float] = None

    @property
    def ret(self) -> float:
        return (self.exit_px / self.entry_px - 1.0) if self.entry_px else 0.0

    @property
    def pnl(self) -> float:
        return (self.exit_px - self.entry_px) * self.qty


def live_trades(store: Store, symbol: str, session: str) -> list[LiveTrade]:
    """Round trips from the `fills` table, in execution order."""
    limits = entry_limits(store, symbol, session)
    out: list[LiveTrade] = []

    pos = 0.0
    e_notional = e_qty = x_notional = x_qty = 0.0
    e_execs = x_execs = 0
    entry_bar: Optional[int] = None
    exit_bar: Optional[int] = None
    outcome = "open"
    limit_px: Optional[float] = None

    for f in store.session_fills(symbol, session):
        qty = float(f["qty"] or 0.0)
        px = float(f["price"] or 0.0)
        if qty <= 0.0:
            continue
        idx = bar_idx_of(f["ts"])
        buy = (f["side"] == "BOT") or (f["role"] == "E")

        if buy:
            if pos <= QTY_EPS:
                entry_bar = idx
                # The limit that was resting when this entry began. Fall back to
                # the most recent one at or before the fill bar.
                cands = [b for b in limits if idx is None or b <= idx]
                limit_px = limits[max(cands)] if cands else None
            e_notional += qty * px
            e_qty += qty
            e_execs += 1
            pos += qty
        else:
            x_notional += qty * px
            x_qty += qty
            x_execs += 1
            exit_bar = idx
            outcome = EXIT_OUTCOME.get(f["role"] or "", "flatten")
            pos -= qty
            if pos <= QTY_EPS and e_qty > 0.0:
                out.append(LiveTrade(
                    entry_bar=entry_bar, exit_bar=exit_bar,
                    entry_px=e_notional / e_qty, exit_px=x_notional / x_qty,
                    qty=x_qty, outcome=outcome,
                    n_entry_execs=e_execs, n_exit_execs=x_execs,
                    limit_px=limit_px))
                pos = 0.0
                e_notional = e_qty = x_notional = x_qty = 0.0
                e_execs = x_execs = 0
                entry_bar = exit_bar = None
                limit_px = None

    # Still long at the end of the record: the flatten did not complete, or the
    # report is being run mid-session. Either way it must be visible.
    if e_qty > 0.0 and pos > QTY_EPS:
        out.append(LiveTrade(entry_bar=entry_bar, exit_bar=None,
                             entry_px=e_notional / e_qty, exit_px=float("nan"),
                             qty=pos, outcome="open", n_entry_execs=e_execs,
                             n_exit_execs=x_execs, limit_px=limit_px))
    return out


# --------------------------------------------------------------- the shadow
@dataclass
class Shadow:
    """What the backtest books on the same bars, with the same config."""
    trades: list[Trade]
    pnl: float
    fills: int
    stop_outs: int
    ran: bool
    reason: str = ""


def shadow_replay(bars: Sequence[Bar], row) -> Shadow:
    """Drive the recorded bars through the live state machine.

    The gate and filter are **not re-decided**. They are replayed from what the
    engine recorded in `daily`, so this diff isolates the order path. Feature
    arithmetic is checked separately (`feature_parity`), which is the right
    place for it: a feature bug and a fill bug want different fixes and mixing
    them into one number hides both.

    The config is the *live* config — tick rounding on, whole shares, §2.4
    limit-price sizing — for the same reason. The only thing that differs from
    the real session is who decided the fills.
    """
    if row is None:
        return Shadow([], 0.0, 0, 0, False, "no daily row")
    if not row["gate_ok"]:
        return Shadow([], 0.0, 0, 0, False, row["gate_reason"] or "gate_off")
    if not row["filter_ok"]:
        return Shadow([], 0.0, 0, 0, False, row["filter_reason"] or "stood_down")
    if not bars:
        return Shadow([], 0.0, 0, 0, False, "no bars recorded")

    capital = row["sleeve_capital"]
    if capital is None:
        return Shadow([], 0.0, 0, 0, False, "no sleeve_capital recorded")

    cfg = SleeveConfig(symbol=row["symbol"], sleeve_capital=float(capital))
    sm = SleeveStateMachine(cfg)
    stats = session_stats(bars)
    gate = sm.begin_session(row["session"], float(row["atr5"]),
                            stats.is_half_day, stats.late_open)
    if not gate.ok:
        # The engine traded a day the replay now refuses. That is a finding, not
        # a reason to give up — surface the disagreement rather than swallow it.
        return Shadow([], 0.0, 0, 0, False, f"shadow gate refused: {gate.reason}")
    filt = sm.apply_morning_filter(float(row["or30"]), float(row["thr80"]),
                                   float(row["pos10"]))
    if not filt.ok:
        return Shadow([], 0.0, 0, 0, False, f"shadow filter refused: {filt.reason}")

    replay_session(list(bars), sm, fill_model="spec")
    return Shadow(sm.trades, sm.pnl, sm.fills, sm.stop_outs, True)


# ------------------------------------------------------------ feature parity
@dataclass
class FeatureCheck:
    name: str
    live: Optional[float]
    recomputed: Optional[float]
    tol: float

    @property
    def ok(self) -> bool:
        if self.live is None or self.recomputed is None:
            return False
        return abs(self.live - self.recomputed) <= self.tol


def feature_parity(bars: Sequence[Bar], row) -> list[FeatureCheck]:
    """Recompute §2.1's session quantities from the recorded bars.

    This is the check that would have caught the `America/Los_Angeles` defect
    without costing a session: if the bars were indexed wrongly, the opening
    range recomputed from them will not match the OR30 the engine recorded.
    """
    if not bars or row is None:
        return []
    stats = session_stats(bars)
    def _get(k):
        v = row[k]
        return None if v is None else float(v)
    return [
        FeatureCheck("or30", _get("or30"), stats.or30, 1e-6),
        FeatureCheck("pos10", _get("pos10"), stats.pos10, 1e-6),
    ]


# ------------------------------------------------------------------ slippage
@dataclass
class SlipRow:
    bar: Optional[int]
    role: str
    side: str
    qty: float
    price: float
    limit_px: Optional[float]
    mid: Optional[float]

    @property
    def vs_limit(self) -> Optional[float]:
        """Signed, in basis points, positive == worse than the limit.

        A BUY filling above its limit and a SELL filling below it are both
        adverse, so the sign is flipped on the sell side.
        """
        if self.limit_px in (None, 0):
            return None
        raw = (self.price / self.limit_px - 1.0) * 1e4
        return raw if self.side == "BOT" else -raw

    @property
    def vs_mid(self) -> Optional[float]:
        if self.mid in (None, 0):
            return None
        raw = (self.price / self.mid - 1.0) * 1e4
        return raw if self.side == "BOT" else -raw


def slippage(store: Store, symbol: str, session: str) -> list[SlipRow]:
    limits = entry_limits(store, symbol, session)
    out = []
    for f in store.session_fills(symbol, session):
        idx = bar_idx_of(f["ts"])
        role = f["role"] or "?"
        bid, ask = f["bid"], f["ask"]
        mid = (float(bid) + float(ask)) / 2.0 if bid and ask else None
        lim = None
        if role == "E":
            cands = [b for b in limits if idx is None or b <= idx]
            lim = limits[max(cands)] if cands else None
        out.append(SlipRow(bar=idx, role=role, side=f["side"] or "",
                           qty=float(f["qty"] or 0.0), price=float(f["price"] or 0.0),
                           limit_px=lim, mid=mid))
    return out


# ------------------------------------------------------------- S10/S11 checks
@dataclass
class FillWithoutQuote:
    """§5 question 1: did a fill occur without the quote reaching the limit?"""
    bar: Optional[int]
    price: float
    limit_px: float
    best_bid_seen: Optional[float]
    n_quotes: int

    @property
    def suspicious(self) -> bool:
        # Only a positive observation counts. With no quotes recorded there is
        # no evidence either way, and the report must not manufacture some —
        # defects 6 and 7 were both checks that fired on absence of evidence.
        return (self.n_quotes > 0 and self.best_bid_seen is not None
                and self.best_bid_seen > self.limit_px)


def fills_without_quotes(store: Store, symbol: str,
                         session: str) -> list[FillWithoutQuote]:
    quotes = store.rows(
        "SELECT * FROM quotes WHERE session=? AND symbol=? ORDER BY ts",
        (session, symbol))
    limits = entry_limits(store, symbol, session)
    out = []
    for f in store.session_fills(symbol, session):
        if (f["role"] or "") != "E":
            continue
        idx = bar_idx_of(f["ts"])
        cands = [b for b in limits if idx is None or b <= idx]
        if not cands:
            continue
        lim = limits[max(cands)]
        seen = [float(q["bid"]) for q in quotes
                if q["bid"] is not None and (bar_idx_of(q["ts"]) or -1) <= (idx or 10**6)]
        out.append(FillWithoutQuote(bar=idx, price=float(f["price"] or 0.0),
                                    limit_px=lim,
                                    best_bid_seen=min(seen) if seen else None,
                                    n_quotes=len(seen)))
    return out


@dataclass
class SameBarReentry:
    """§5 question 2, and the sharpest available test of S10.

    S10's claim is that the 5-minute backtest books a re-entry at a price that
    had already traded *before* the exit it follows. Live, the re-entry order
    is sent after the exit fills, so it can only trade against prints that come
    after it.

    **What this can and cannot prove.** A live re-entry priced below the exit
    it followed is *not* impossible — the market may simply have fallen after
    the exit, which is an ordinary and profitable event. So `live_better` is
    not a defect detector on its own. What isolates S10 is the comparison:
    `shadow_advantage_bp` on events both sources saw, and the count of
    re-entries the shadow books that the live session never had at all.
    """
    bar: int
    prev_exit_px: float
    live_entry_px: Optional[float]
    shadow_entry_px: Optional[float]

    @property
    def live_better(self) -> Optional[bool]:
        """Did the live re-entry get in below the price it had just sold at?

        §5 question 2 asks for this directly. "At or worse" — i.e. False — is
        the answer S10 predicts should dominate.
        """
        if self.live_entry_px is None:
            return None
        return self.live_entry_px < self.prev_exit_px

    @property
    def shadow_better(self) -> Optional[bool]:
        if self.shadow_entry_px is None:
            return None
        return self.shadow_entry_px < self.prev_exit_px

    @property
    def shadow_advantage_bp(self) -> Optional[float]:
        """How much cheaper the backtest got in, on an event both sources saw.

        Positive means the shadow bought below the live fill — the S10
        exposure, measured in the only place it can be measured directly.
        """
        if self.live_entry_px is None or not self.shadow_entry_px:
            return None
        return (self.live_entry_px / self.shadow_entry_px - 1.0) * 1e4


def same_bar_reentries(live: Sequence[LiveTrade],
                       shadow: Sequence[Trade]) -> list[SameBarReentry]:
    """Re-entries that began in the bar the previous trade exited in."""
    out: list[SameBarReentry] = []

    def _pairs_live():
        for a, b in zip(live, live[1:]):
            if a.exit_bar is not None and b.entry_bar == a.exit_bar:
                yield a.exit_bar, a.exit_px, b.entry_px
    def _pairs_shadow():
        for a, b in zip(shadow, shadow[1:]):
            if b.entry_bar == a.exit_bar:
                yield a.exit_bar, a.exit_px, b.entry_px

    shadow_by_bar = {bar: (xpx, epx) for bar, xpx, epx in _pairs_shadow()}
    for bar, xpx, epx in _pairs_live():
        s = shadow_by_bar.pop(bar, None)
        out.append(SameBarReentry(bar=bar, prev_exit_px=xpx, live_entry_px=epx,
                                  shadow_entry_px=s[1] if s else None))
    # Shadow re-entries the live session never had — the S10 population that
    # simply does not exist in reality. These are the most important rows.
    for bar, (xpx, epx) in sorted(shadow_by_bar.items()):
        out.append(SameBarReentry(bar=bar, prev_exit_px=xpx,
                                  live_entry_px=None, shadow_entry_px=epx))
    return sorted(out, key=lambda r: r.bar)


# ------------------------------------------------------------ §8 monitoring
def load_baselines(root: str = _BAND_LAB) -> dict[tuple[str, str], float]:
    """§8's published baselines, from the file `parity.py` regenerates."""
    path = os.path.join(root, "phase1", "out", "monitoring_expectations.csv")
    out: dict[tuple[str, str], float] = {}
    if not os.path.exists(path):
        return out
    with open(path, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            try:
                out[(r["sleeve"], r["metric"])] = float(r["measured"])
            except (KeyError, TypeError, ValueError):
                continue
    return out


@dataclass
class Weekly:
    symbol: str
    sessions: int = 0
    on_days: int = 0
    fills: int = 0
    outcomes: dict = field(default_factory=dict)
    day_returns: list[float] = field(default_factory=list)

    @property
    def on_rate(self) -> Optional[float]:
        return 100.0 * self.on_days / self.sessions if self.sessions else None

    @property
    def fills_per_on_day(self) -> Optional[float]:
        return self.fills / self.on_days if self.on_days else None

    @property
    def gross_bp(self) -> Optional[float]:
        if not self.day_returns:
            return None
        return 1e4 * sum(self.day_returns) / len(self.day_returns)

    @property
    def worst_day(self) -> Optional[float]:
        return 100.0 * min(self.day_returns) if self.day_returns else None

    def outcome_pct(self, name: str) -> Optional[float]:
        total = sum(self.outcomes.values())
        return 100.0 * self.outcomes.get(name, 0) / total if total else None


def weekly(store: Store, symbols: Optional[Sequence[str]] = None,
           sessions: Optional[Sequence[str]] = None) -> dict[str, Weekly]:
    sessions = list(sessions or sessions_in(store))
    acc: dict[str, Weekly] = {}
    for s in sessions:
        for sym in (symbols or symbols_in(store, s)):
            row = daily_row(store, sym, s)
            if row is None:
                continue
            w = acc.setdefault(sym, Weekly(sym))
            w.sessions += 1
            traded = bool(row["gate_ok"]) and bool(row["filter_ok"])
            if not traded:
                continue
            w.on_days += 1
            trades = live_trades(store, sym, s)
            w.fills += len(trades)
            # Sum of per-trade returns — the same quantity §8's bp figures are,
            # and independent of `f` and of the recorded capital.
            w.day_returns.append(
                sum(t.ret for t in trades if t.outcome != "open"))
            for t in trades:
                w.outcomes[t.outcome] = w.outcomes.get(t.outcome, 0) + 1
    return acc


# ------------------------------------------------------------------ printing
def _rule(title: str = "", ch: str = "=", width: int = 78) -> str:
    return ch * width if not title else f"{title} ".ljust(width, ch)


def print_session_report(store: Store, session: str,
                         symbols: Optional[Sequence[str]] = None) -> int:
    """The daily report. Returns the number of findings that need a human."""
    findings = 0
    syms = list(symbols or symbols_in(store, session))
    print(_rule())
    print(f"SESSION {session_label(session)} — shadow parity and fill quality")
    print(_rule())
    if not syms:
        print("\nNo sleeves recorded for this session.")
        return 0

    for sym in syms:
        row = daily_row(store, sym, session)
        bars = recorded_bars(store, sym, session)
        live = live_trades(store, sym, session)
        sh = shadow_replay(bars, row)

        print(f"\n{_rule(sym, '-')}")
        if row is not None:
            print(f"  gate    {'ON ' if row['gate_ok'] else 'OFF'}  "
                  f"{row['gate_reason'] or '':<32} atr5={_fmt(row['atr5'])}")
            print(f"  filter  {'ON ' if row['filter_ok'] else 'OFF'}  "
                  f"{row['filter_reason'] or '':<32} "
                  f"or30={_fmt(row['or30'])} thr80={_fmt(row['thr80'])} "
                  f"pos10={_fmt(row['pos10'], 3)}")
            print(f"  capital {_fmt(row['sleeve_capital'], 0)}   bars recorded: {len(bars)}")

        # --- 1. feature parity
        checks = feature_parity(bars, row)
        for c in checks:
            if not c.ok:
                findings += 1
                print(f"  [FINDING] {c.name}: engine recorded {_fmt(c.live, 4)}, "
                      f"recomputed from the recorded bars {_fmt(c.recomputed, 4)}")

        # --- 2. shadow parity
        print(f"\n  shadow: {'ran' if sh.ran else 'did not run — ' + sh.reason}")
        if sh.ran or live:
            print(f"    {'':<4} {'LIVE':<38}{'SHADOW (backtest fills)':<38}")
            print(f"    {'#':<4} {'bars':<9} {'entry':>8} {'exit':>8}  {'out':<9}"
                  f"{'bars':<9} {'entry':>8} {'exit':>8}  {'out':<9}")
            for i in range(max(len(live), len(sh.trades))):
                lt = live[i] if i < len(live) else None
                st = sh.trades[i] if i < len(sh.trades) else None
                blank = f"{'—':<9} {'—':>8} {'—':>8}  {'—':<9}"
                lc = (f"{str(lt.entry_bar) + '>' + str(lt.exit_bar):<9} "
                      f"{_fmt(lt.entry_px):>8} {_fmt(lt.exit_px):>8}  "
                      f"{lt.outcome:<9}") if lt else blank
                sc = (f"{str(st.entry_bar) + '>' + str(st.exit_bar):<9} "
                      f"{_fmt(st.entry_px):>8} {_fmt(st.exit_px):>8}  "
                      f"{st.outcome:<9}") if st else blank
                print(f"    {i+1:<4} {lc}{sc}")

            # Both sides are the *sum of per-trade returns*, which is what
            # `sleeve.py` accumulates into `sm.pnl` and what §8's bp figures
            # are. Deriving the live number from dollar P&L over sleeve capital
            # would instead carry a factor of `f`, which the backtest's figure
            # does not have and which the `daily` row does not record.
            lbp = 1e4 * sum(t.ret for t in live if t.outcome != "open")
            sbp = 1e4 * sh.pnl
            print(f"\n    trades   live {len(live):<3}  shadow {len(sh.trades)}")
            print(f"    bp/day   live {_fmt(lbp):<7}  shadow {_fmt(sbp):<7}  "
                  f"gap {_fmt(lbp - sbp)}   (sum of per-trade returns)")
            if len(live) != len(sh.trades) and sh.ran:
                findings += 1
                print(f"    [FINDING] trade-count mismatch: the fill models "
                      f"disagree on how many round trips this session held")

        # --- multi-execution entries (defect 8's signature)
        multi = [t for t in live if t.n_entry_execs > 1]
        if multi:
            print(f"\n  entries settled in multiple executions: {len(multi)} "
                  f"({', '.join(str(t.n_entry_execs) for t in multi)}) — "
                  f"the bracket must have covered the whole position each time")

        # --- 3. S10/S11
        q1 = [f for f in fills_without_quotes(store, sym, session) if f.suspicious]
        if q1:
            findings += len(q1)
            print(f"\n  [FINDING] {len(q1)} entry fill(s) with no recorded quote "
                  f"reaching the limit:")
            for f in q1:
                print(f"      bar {f.bar}: filled {_fmt(f.price)} on a limit of "
                      f"{_fmt(f.limit_px)}, best bid seen {_fmt(f.best_bid_seen)} "
                      f"over {f.n_quotes} quotes")

        reentries = same_bar_reentries(live, sh.trades)
        if reentries:
            print(f"\n  same-bar re-entries (S10 — the sharpest available test):")
            for r in reentries:
                adv = r.shadow_advantage_bp
                print(f"      bar {r.bar}: prev exit {_fmt(r.prev_exit_px)}  "
                      f"live {_fmt(r.live_entry_px)}"
                      f"{' (below the exit)' if r.live_better else ''}  "
                      f"shadow {_fmt(r.shadow_entry_px)}"
                      f"{' (below the exit)' if r.shadow_better else ''}"
                      + (f"  shadow advantage {_fmt(adv)} bp" if adv else ""))

            both = [r for r in reentries if r.shadow_advantage_bp is not None]
            if both:
                mean_adv = sum(r.shadow_advantage_bp for r in both) / len(both)
                print(f"      mean shadow advantage over {len(both)} shared "
                      f"event(s): {_fmt(mean_adv)} bp")
            # §5 question 2, answered directly.
            answered = [r for r in reentries if r.live_better is not None]
            if answered:
                worse = sum(1 for r in answered if not r.live_better)
                print(f"      §5 Q2 — live re-entry at or worse than the price "
                      f"just sold: {worse} of {len(answered)}")
            ghosts = [r for r in reentries if r.live_entry_px is None]
            if ghosts:
                print(f"      {len(ghosts)} re-entry(ies) the backtest books that "
                      f"the live session never had — the S10 population")

        # --- 4. slippage
        slips = slippage(store, sym, session)
        graded = [s for s in slips if s.vs_limit is not None]
        if graded:
            avg = sum(s.vs_limit for s in graded) / len(graded)
            worse = sum(1 for s in graded if s.vs_limit > 0)
            print(f"\n  slippage vs the resting limit: {len(graded)} entry "
                  f"execution(s), mean {_fmt(avg)} bp, {worse} adverse "
                  f"(positive == worse than the limit)")

    print(f"\n{_rule()}")
    print(f"{findings} finding(s) needing a human." if findings
          else "No findings. Shadow and live agree, and no fill-quality flag fired.")
    print(_rule())
    return findings


def print_weekly_report(store: Store, symbols: Optional[Sequence[str]] = None,
                        sessions: Optional[Sequence[str]] = None) -> int:
    """§8's comparison against the published baselines. Returns break count."""
    base = load_baselines()
    acc = weekly(store, symbols, sessions)
    breaks = 0
    print(_rule())
    print("§8 MONITORING — live against the published baselines")
    print(_rule())
    if not base:
        print("\n  phase1/out/monitoring_expectations.csv not found — run "
              "`python3 band_lab/phase1/parity.py` to regenerate it.")
    for sym, w in sorted(acc.items()):
        print(f"\n{_rule(sym, '-')}")
        print(f"  {w.sessions} session(s), {w.on_days} ON-day(s), "
              f"{w.fills} round trip(s)")
        rows = [
            ("fills_per_ON_day", w.fills_per_on_day, 2),
            ("ON_day_rate_%", w.on_rate, 1),
            ("target_%", w.outcome_pct("target"), 1),
            ("stop_%", w.outcome_pct("stop"), 1),
            ("flatten_%", w.outcome_pct("flatten"), 1),
            ("gross_bp_per_ON_day", w.gross_bp, 1),
            ("worst_day_%", w.worst_day, 2),
        ]
        print(f"    {'metric':<22} {'live':>10} {'§8':>10} {'deviation':>12}")
        for name, val, nd in rows:
            exp = base.get((sym, name))
            dev = None
            if val is not None and exp not in (None, 0):
                dev = (val - exp) / abs(exp)
            flag = ""
            # §8: the >20% rule applies to fill counts and ON-rates. bp figures
            # are far too noisy on a short window for a deviation to mean
            # anything, and PHASE2_PARITY S11 says to expect 54-64% of the
            # published number anyway — flagging that would be noise by design.
            if (dev is not None and w.sessions >= MIN_SESSIONS_FOR_BREAK
                    and name in ("fills_per_ON_day", "ON_day_rate_%")
                    and abs(dev) > STRUCTURAL_BREAK):
                flag, breaks = "  <-- STRUCTURAL", breaks + 1
            print(f"    {name:<22} {_fmt(val, nd):>10} {_fmt(exp, nd):>10} "
                  f"{_pct(dev) if dev is not None else '—':>12}{flag}")

        if w.sessions < MIN_SESSIONS_FOR_BREAK:
            print(f"\n    {w.sessions} session(s) — below the "
                  f"{MIN_SESSIONS_FOR_BREAK} §8's monthly rule needs, so no "
                  f"deviation above is flagged. A single week proves nothing.")
    print(f"\n{_rule()}")
    print(f"{breaks} structural break(s) — investigate." if breaks
          else "No structural break against §8 on the >20% rule.")
    print(_rule())
    return breaks


# ------------------------------------------------------------------ CSV out
def write_csvs(store: Store, outdir: str, session: str,
               symbols: Optional[Sequence[str]] = None) -> list[str]:
    os.makedirs(outdir, exist_ok=True)
    written = []
    trade_path = os.path.join(outdir, f"parity_{session}.csv")
    with open(trade_path, "w", newline="", encoding="utf-8") as fh:
        wr = csv.writer(fh)
        wr.writerow(["session", "symbol", "n", "src", "entry_bar", "exit_bar",
                     "entry_px", "exit_px", "qty", "outcome", "ret_bp"])
        for sym in (symbols or symbols_in(store, session)):
            row = daily_row(store, sym, session)
            bars = recorded_bars(store, sym, session)
            for i, t in enumerate(live_trades(store, sym, session), 1):
                wr.writerow([session, sym, i, "live", t.entry_bar, t.exit_bar,
                             f"{t.entry_px:.4f}", f"{t.exit_px:.4f}", t.qty,
                             t.outcome, f"{t.ret * 1e4:.2f}"])
            for i, t in enumerate(shadow_replay(bars, row).trades, 1):
                wr.writerow([session, sym, i, "shadow", t.entry_bar, t.exit_bar,
                             f"{t.entry_px:.4f}", f"{t.exit_px:.4f}", t.qty,
                             t.outcome, f"{t.ret * 1e4:.2f}"])
    written.append(trade_path)

    slip_path = os.path.join(outdir, f"slippage_{session}.csv")
    with open(slip_path, "w", newline="", encoding="utf-8") as fh:
        wr = csv.writer(fh)
        wr.writerow(["session", "symbol", "bar", "role", "side", "qty", "price",
                     "limit_px", "mid", "vs_limit_bp", "vs_mid_bp"])
        for sym in (symbols or symbols_in(store, session)):
            for s in slippage(store, sym, session):
                wr.writerow([session, sym, s.bar, s.role, s.side, s.qty,
                             f"{s.price:.4f}",
                             "" if s.limit_px is None else f"{s.limit_px:.4f}",
                             "" if s.mid is None else f"{s.mid:.4f}",
                             "" if s.vs_limit is None else f"{s.vs_limit:.2f}",
                             "" if s.vs_mid is None else f"{s.vs_mid:.2f}"])
    written.append(slip_path)
    return written


# ---------------------------------------------------------------------- CLI
def default_db() -> str:
    return os.path.join(_HERE, "out", "live.db")


def main(argv: Optional[Sequence[str]] = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[1],
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--db", default=default_db(), help="path to live.db")
    p.add_argument("--session", help="YYYYMMDD (default: the latest in the db)")
    p.add_argument("--symbol", action="append", dest="symbols",
                   help="restrict to a sleeve; repeatable")
    p.add_argument("--weekly", action="store_true", help="the §8 comparison")
    p.add_argument("--all", action="store_true", help="every session, then §8")
    p.add_argument("--csv", metavar="DIR", help="also write the per-trade CSVs")
    a = p.parse_args(argv)

    if not os.path.exists(a.db):
        print(f"no database at {a.db}\n"
              f"The engine writes it at `live/out/live.db`; pass --db if yours "
              f"is elsewhere.", file=sys.stderr)
        return 2

    store = Store(a.db)
    try:
        all_sessions = sessions_in(store)
        if not all_sessions:
            print("The database has no sessions yet — nothing to report on.")
            return 0

        findings = 0
        if a.weekly and not a.all:
            return 1 if print_weekly_report(store, a.symbols) else 0

        targets = all_sessions if a.all else [a.session or all_sessions[-1]]
        for s in targets:
            if s not in all_sessions:
                print(f"session {s} is not in the database. Available: "
                      f"{', '.join(all_sessions[-10:])}", file=sys.stderr)
                return 2
            findings += print_session_report(store, s, a.symbols)
            if a.csv:
                for path in write_csvs(store, a.csv, s, a.symbols):
                    print(f"  wrote {path}")
            print()

        if a.all:
            findings += print_weekly_report(store, a.symbols)
        return 1 if findings else 0
    finally:
        store.close()


if __name__ == "__main__":
    raise SystemExit(main())
